Annotations Batch Job - Type Filter on API Call
biobankinguk/biobankinguk pull request #100
Opened 2021-02-05 13:54 UTC by JosephLavagna

- Filters Annotations from API by list of types
- Fixed duplicate annotation check before pushed to database

2021-02-05 14:07 UTC, Flemingjp requested changes

2021-02-05 14:07 UTC, Flemingjp commented on src/Publications/Publications/Services/EpmcWebService.cs
> +
Can initialize the list directly with the values. 

```c#
var types = new List<string>()
{
    "Diseases",
    "Organ Tissue"
};
```
Should be able to add the `type` query to the parameters dictionary for the QueryHelper to parse automatically. I'm assuming current solution is a workaround for EMPC use of multiple `type` and QueryHelpers lack of support for it?

```c#
var parameters = new Dictionary<string, string>()
{
    { "articleIds", $"{source}:{publicationId}" },
    { "format", "JSON" },
    { "type", string.Join("&type=", types) }
};
```

2021-02-05 14:24 UTC, beforan commented on src/Publications/Publications/Services/EpmcWebService.cs
> +
or use [Flurl](https://flurl.dev/docs/fluent-url/)

notably:
> Url.QueryParams is a special collection type that maintains order and allows duplicate names, but is optimized for the typical case of unique names

2021-02-05 14:24 UTC, JosephLavagna commented on src/Publications/Publications/Services/EpmcWebService.cs
> +
yep exactly - epmc uses multiple 'type' for its endpoint and QueryHelper only supports the use of a dictionary. Unfortunately that solution doesn't return any annotations.

2021-02-05 14:38 UTC, beforan requested changes

2021-02-05 14:38 UTC, beforan commented on src/Publications/Publications/Services/AnnotationService.cs
> +            var annList = annotationList.GroupBy(x => x.Name).Select(x => x.First()).ToList();
`ToHashSet().ToList()` will do this but look less complex ;) (and the framework is probably more efficient than you ;))

Also, does it need to be a list? could just `ToHashSet()` and then iterate over that instead of a list?

Yes, HashSet is my new favourite type. Yes, it's your fault.

2021-02-05 14:38 UTC, beforan commented on src/Publications/Publications/Services/AnnotationService.cs
>                  var older = existingAnnotations.Select(x => x.Annotation).Where(a => a.AnnotationId == newer.AnnotationId).FirstOrDefault();
you can inline this. Most LINQ selectors like `First()` accept filter expressions.

sooo: `existingAnnotations.Select(x => x.Annotation).FirstOrDefault(a => a.AnnotationId == newer.AnnotationId);`

2021-02-05 14:41 UTC, beforan commented on src/Publications/Publications/Services/AnnotationService.cs
> +            var annList = annotationList.GroupBy(x => x.Name).Select(x => x.First()).ToList();
actually, your grouping on a property so it might be more complicated than i thought...

2021-02-08 11:46 UTC, Flemingjp approved these changes

2021-02-08 13:46 UTC, beforan approved these changes

2021-02-08 13:46 UTC, merged