Add PreservationType to Samples The API
biobankinguk/biobankinguk pull request #106
Opened 2021-02-09 11:56 UTC by Flemingjp

2021-02-09 11:59 UTC, Flemingjp commented on src/Api/SubmissionAzureFunction/Services/ReferenceDataReadService.cs
> +            => await _db.PreservationTypes.AsNoTracking().ToListAsync();
Is caching required - how does this work out if the reference data is changed on the Directory side?

2021-02-09 12:34 UTC, beforan commented on src/Api/SubmissionAzureFunction/Services/ReferenceDataReadService.cs
> +            => await _db.PreservationTypes.AsNoTracking().ToListAsync();
> how does this work if the [...] data is changed

I mean, that is the million dollar question in all caching scenarios.

I don't think we need caching of this data yet.

If and when we do, we will look at appropriate strategies for invalidation on source data change, or "eventual consistency", but that's for another day.

2021-02-09 13:14 UTC, Flemingjp commented on src/Api/SubmissionAzureFunction/Services/ReferenceDataReadService.cs
> +            => await _db.PreservationTypes.AsNoTracking().ToListAsync();
PBI 30996

2021-02-10 10:12 UTC, Flemingjp commented on src/Data/BiobanksDbContext.cs
> +        public DbSet<Status> Status { get; set; }
Biobanks table is currently called `Status` vs `Statuses` therefore was causing errors. Might be nicer to rename the table to `Statuses` as all other tables are plural.

2021-02-10 12:07 UTC, Flemingjp commented on src/Api/SubmissionAzureFunction/Services/ReferenceDataReadService.cs
> +                    (x.MaterialTypeGroups?.Any() ?? false));
Added condition to ensure there are some MaterialTypeGroups. It wasn't doing this check, causing NPE in several places.

2021-02-10 12:08 UTC, Flemingjp commented on src/Api/SubmissionAzureFunction/Services/SampleWriteService.cs
>                  .Where(x => x.OrganisationId == organisationId)
Same issue with `Statuses`

2021-02-10 16:08 UTC, beforan requested changes

2021-02-10 16:08 UTC, beforan commented on src/Data/BiobanksDbContext.cs
> +        public DbSet<Status> Status { get; set; }
yes please to the table rename.

2021-02-10 16:08 UTC, beforan commented on src/Api/SubmissionAzureFunction/Services/SampleWriteService.cs
> +                catch
This is almost certainly not the right thing to do

Why are we catching all exceptions in the above block and then doing nothing?

- Can we catch only specific actions?
- What should we do instead of nothing?

2021-02-10 16:08 UTC, beforan commented on src/Api/SubmissionAzureFunction/Services/SampleWriteService.cs
>                  .Where(x => x.OrganisationId == organisationId)
same issue?

2021-02-10 16:11 UTC, Flemingjp commented on src/Api/SubmissionAzureFunction/Services/SampleWriteService.cs
> +                catch
Not sure what has changed here? I'll check and get back to you

2021-02-10 16:16 UTC, Flemingjp commented on src/Api/SubmissionAzureFunction/Services/SampleWriteService.cs
>                  .Where(x => x.OrganisationId == organisationId)
Well similar, the table is called `LiveSamples` where the context was expecting `Samples`

2021-02-12 08:44 UTC, beforan approved these changes

2021-02-12 09:05 UTC, JosephLavagna approved these changes

2021-02-12 09:14 UTC, merged