Upgrade DataSeeder to .NET 5 / EF Core
biobankinguk/biobankinguk pull request #111
Opened 2021-02-12 11:40 UTC by Flemingjp

Upgrade of the DataSeeder to .NET 5 and EF Core DbContext

2021-02-16 14:39 UTC, JosephLavagna approved these changes

2021-02-16 16:21 UTC, JosephLavagna submitted a review, later dismissed

2021-02-17 13:10 UTC, beforan requested changes

2021-02-17 13:10 UTC, beforan commented on src/DataSeed/DataSeed.csproj
> +    <TargetFramework>net5.0-windows7.0</TargetFramework>
why windows? it shouldn't do anything os specific?

2021-02-17 13:10 UTC, beforan commented on src/DataSeed/DataSeed.csproj
> +    <ProjectReference Include="..\Directory\Services\Services.csproj" />
bit awkward it depends on the directory services. Rather indicates they should be moved up to a top-level "common" sort of project

2021-02-17 13:10 UTC, beforan commented on src/DataSeed/DataSeed.csproj
> +    <ProjectReference Include="..\Directory\Services\Services.csproj" />
granted modularising and moving the shared bits right now might be beyond the scope of this PR but i definitely think it's desirable

2021-02-17 13:16 UTC, blargly submitted a review, later dismissed

2021-02-17 13:27 UTC, blargly approved these changes

2021-02-17 13:29 UTC, beforan approved these changes

2021-02-17 13:30 UTC, merged