B: Improve search typeahead experience to accomodate "other terms"
biobankinguk/biobankinguk pull request #117
Opened 2021-02-16 21:35 UTC by shakisparki

currently, typeahead suggests (autocompletes) the primary name of a disease status.

Once other terms are present, we should only show one suggestion per primary name (as now), but have a richer results view, something like:

----
Primary name
(other term being autocompleted)
(...other possible terms)
----

This PR presents the results in the exact way as shown above at the cost of extra logic. See img below

![image](https://user-images.githubusercontent.com/26871554/108124206-d70c8e00-709e-11eb-8544-0e99027a3e6c.png)

2021-02-19 09:55 UTC, Flemingjp requested changes

2021-02-19 09:55 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Controllers/SearchController.cs
Since this result is then transformed to a OntologyTermModel straight afterwards - is the AutoMapper a bit redundant. Should be able to map directly to an OntologyTermModel manually?

2021-02-19 09:55 UTC, Flemingjp commented on src/Directory/Services/BiobankReadService.cs
>          }
Any chance of splitting this code up for the sake of clarity. There's a lot going on in one place, and it should be as easy to read where possible.

2021-02-19 09:55 UTC, Flemingjp commented on src/Directory/Search/Elastic/BaseElasticSearchProvider.cs
> +        }
Same with clarity here - probably can make it clearer by trying to use LINQ to reduce the three explicit for loops. Thinking something like this (untested idea).

```c#
protected static IEnumerable<OntologyTermsSummary> ExtractOntologyOtherTermsHits(ISearchResponse<BaseDocument> searchResponse)
{
    var ontologyTerms = searchResponse.Aggregations
            .Terms("diagnoses")
            .Buckets
            .Select(x => 
                new OntologyTerm
                {
                    OntologyTerm = x.Key,
                    MatchingOtherTerms = new ();
                }
            );

    foreach (var ontologyTerm in ontologyTerms)
    {
        searchResponse.Hits
            .Where(x => x.Source.OntologyTerm.ToLower() == ontologyTerm.OntologyTerm)
            .Where(x => 
                !ontologyTerm.MatchingOtherTerms.Any(y => 
                    y == terms.Highlight["ontologyOtherTerms.name"].FirstOrDefault()
                )
            )
            .ToList()
            .ForEach(ontologyTerm.MatchingOtherTerms.Add)
    }

    return ontologyTerms;
}
```

I think clarity in the search project should be priority as a lot of the code is already unknown and unclear.

2021-02-22 12:22 UTC, shakisparki commented on src/Directory/Search/Elastic/BaseElasticSearchProvider.cs
> +        }
In terms of clarity, I think having explicit foreach statement does that better than compact LinQ statements especially for the complex search queries. In terms of compactness of code, I don't seem to be able to get your sample to work correctly. If you can get a working code then please do forward and I will happily replace the block.

2021-02-23 14:40 UTC, beforan approved these changes

2021-02-24 16:10 UTC, blargly approved these changes

2021-02-24 16:39 UTC, Flemingjp approved these changes

2021-02-24 16:44 UTC, merged