Superuser - Build Index Functionality
biobankinguk/biobankinguk pull request #122
Opened 2021-02-18 17:25 UTC by bradthompson995

The configure-search script from the elastic-search directory has been integrated into the superuser directory in the form of a Build Index button which deletes the index and the builds the index from the supplied JSON files, which are stored in the 'App_Config' folder within the web directory with the other JSON files.  

It also then calls the existing rebuild index function to populate the index.

2021-02-19 10:05 UTC, Flemingjp reviewed
Looking good so far - comments are just suggestions you may as well have whilst working on this PR actively

2021-02-19 10:05 UTC, Flemingjp commented on src/Directory/Services/BiobankIndexService.cs
> +
Can be simply written as

```c#
var _navPaths = new List<string>()
{
    HostingEnvironment.MapPath(@"~/App_Config/capabilities.json"),
    HostingEnvironment.MapPath(@"~/App_Config/collections.json")
};
```

2021-02-19 10:05 UTC, Flemingjp commented on src/Directory/Services/BiobankIndexService.cs
> +                    }
Not sure if you really need to use two seperate HttpClients. You shouldnt need to set the base address either if you're using the the searchBase in the Delete/Put calls.

2021-02-19 10:05 UTC, Flemingjp commented on src/Directory/Services/BiobankIndexService.cs
> +                }
@beforan will probably want some logging to Application Insights here 😉. Saying that @beforan if we were to start more extension AI logging, would it be worth writing a AILogger and using that throughout?

```c#
var ai = new TelemetryClient();
ai.LogError() // Something to that effect
```

2021-02-26 12:36 UTC, Flemingjp submitted a review, later dismissed

2021-02-26 15:08 UTC, beforan requested changes

2021-02-26 15:08 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/SuperUserController.cs
> +            await _indexService.BuildIndex();
If any handled exceptions (http or file) occurred, we can set a failure feedback message appropriately, and not proceed with the rest of this method

2021-02-26 15:08 UTC, beforan commented on src/Directory/Biobanks.Web/App_Config/capabilities.json
> +﻿{
these files are duplicated from the ones in the elastic search folder, now?

Having them in 2 places in the repo will be a nightmare to keep in sync if they change, and they don't really belong to the directory, they are just used by it.

I think they should be put in place possibly when publishing. Can the csproj reference the ones on disk higher up? (I don't see why not). If not, then we can copy them in as content in the deployment pipeline.

2021-03-01 09:16 UTC, Flemingjp approved these changes

2021-03-01 13:58 UTC, beforan approved these changes

2021-03-01 14:48 UTC, merged