Move Migrations To EFCore DbContext
biobankinguk/biobankinguk pull request #124
Opened 2021-02-19 14:23 UTC by Flemingjp

2021-02-19 14:29 UTC, Flemingjp commented on src/DataSeed/Transforms/UrlTransformer.cs
> +            }
@beforan Am I right in thinking that since the scheme is mistyped, the actual scheme has been parsed as the Host and the Host as the PathAndQuery?

2021-02-19 14:46 UTC, beforan requested changes

2021-02-19 14:46 UTC, beforan commented on src/DataSeed/Data/DirectoryConfigs.cs
> +                Key = "site.display.aboutpage",
I think all this content belongs specifically to the Directory app, so it should probably be responsible for ensuring it's present. Probably on app startup.

2021-02-19 14:46 UTC, beforan commented on src/DataSeed/Transforms/UrlTransformer.cs
> +            }
I can't remember the exact issue, but I don't think this data fix is really suitable being in the seeder.

It's more like a utility for if we encoutner broken URLs. Good times to run it might be on Directory startup, or we could trigger it from the SuperUser panel instead. Just as another piece in that toolkit.

2021-03-01 11:57 UTC, Flemingjp commented on src/Directory/Data/BiobanksDbInitializer.cs
> +        private void FixOrganisationUrls(BiobanksDbContext context)
Do we want this as SuperUser tool instead? @beforan @blargly

2021-03-01 13:57 UTC, beforan commented on src/Directory/Data/BiobanksDbInitializer.cs
> +        private void FixOrganisationUrls(BiobanksDbContext context)
not a bad shout at all. I'm up for it

2021-03-01 15:07 UTC, blargly approved these changes

2021-03-02 09:06 UTC, beforan approved these changes

2021-03-02 09:06 UTC, merged