Added migration for PublicationAnnotations join table
biobankinguk/biobankinguk pull request #132
Opened 2021-03-04 17:05 UTC by JosephLavagna

- Added migration to create PublicationAnnotations Join table after it was deleted when src/Data proj was moved to EF Core 5.
- PublicationAnnotations table will need to be deleted on Test and Prod before merge or may cause migration issues.
- PublicationAnnotation entity in Publications solution has been changed to match newly created join table.

2021-03-04 21:28 UTC, Flemingjp approved these changes

2021-03-05 08:56 UTC, beforan requested changes
just blocking the merge while I check some stuff out. will review with comments after my investigations ;)

2021-03-05 09:33 UTC, beforan requested changes

2021-03-05 09:33 UTC, beforan commented on src/Data/BiobanksDbContext.cs
> +            model.Entity<Publication>()
I don't think this fluent config is necessary, but please confirm.

2021-03-05 09:33 UTC, beforan commented on src/Data/Migrations/20210304151621_PublicationAnnotationsJoinTbl.cs
> +    public partial class PublicationAnnotationsJoinTbl : Migration
Remove this migration. A Join table already exists for `Publications` and `Annotations` in the `Initial` migration.

Test to confirm it works as needed - any configuration changes for the join entity should be done in fluent config as per these docs:

https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#join-entity-type-configuration

2021-03-05 09:33 UTC, beforan commented on src/Directory/Data/BiobanksDbContext.cs
> +            modelBuilder.Entity<Publication>()
This config will need amending to match whatever the .NET5 context ends up doing with the join table ;)

2021-03-05 09:33 UTC, beforan commented on src/Publications/Publications/PublicationDbContext.cs
> +                .HasKey(bc => new { bc.PublicationsId, bc.AnnotationsId });
I notice that this PR doesn't update the Core 3.1 `LegacyData` context?

Is this a good time to move this function off of its own separate context and instead onto the `LegacyData` one. That way, we have fewer contexts and we move towards all .NET Core 3.1 code using a single context (like they will use a single .NET5/6/whatever context one day)

2021-03-16 08:45 UTC, beforan commented on src/Publications/Publications/PublicationDbContext.cs
> +                .HasKey(bc => new { bc.PublicationsId, bc.AnnotationsId });
`LegacyData` is no more. Carry on.

2021-03-30 07:57 UTC, closed without merging