Migrations and Context Fixes
biobankinguk/biobankinguk pull request #134
Opened 2021-03-05 12:04 UTC by Flemingjp

2021-03-05 14:07 UTC, beforan requested changes

2021-03-05 14:07 UTC, beforan commented on src/Data/Data.csproj
> +  <ItemGroup>
don't believe this project should have a Migrations folder?

2021-03-05 14:11 UTC, blargly approved these changes

2021-03-05 14:23 UTC, beforan requested changes

2021-03-05 14:23 UTC, beforan commented on src/Data/Data.csproj
> +  <ItemGroup>
Sorry I was looking at the `Entities.csproj` reference above, instead of what file this actually was '-.-

Either way, if `Migrations/` isn't empty (it shouldn't be) it doesn't need explicitly including

2021-03-05 14:26 UTC, beforan approved these changes

2021-03-08 09:20 UTC, blargly approved these changes

2021-03-08 09:22 UTC, JosephLavagna approved these changes

2021-03-08 09:22 UTC, merged