AB#31643 Biobank admin page details
biobankinguk/biobankinguk pull request #160
Opened 2021-03-23 12:36 UTC by blargly

Added the rest of the Biobank admin page functionality, barring password generation which is in a new PBI.

Main Biobanks list in ADAC section now contains an admin column, which links to the new view.

2021-03-23 14:41 UTC, JosephLavagna submitted a review, later dismissed

2021-03-24 14:55 UTC, beforan requested changes

2021-03-24 14:55 UTC, beforan commented on src/Directory/Biobanks.Web/Views/ADAC/Biobanks.cshtml
> +                        <td> </td>
any reason we're leaving these empty cells here? can't they be removed?

2021-03-24 14:55 UTC, beforan commented on src/Directory/Biobanks.Web/Views/ADAC/Biobanks.cshtml
> +                        <td> </td>
(and their corresponding headers `<th>`)

2021-03-24 15:26 UTC, blargly commented on src/Directory/Biobanks.Web/Views/ADAC/Biobanks.cshtml
> +                        <td> </td>
Removed two empty headers and cells. One header remaining as the remaining cell holds our actions.

2021-03-24 16:04 UTC, beforan approved these changes

2021-03-24 16:08 UTC, JosephLavagna approved these changes

2021-03-24 16:08 UTC, merged