AB#32512: Age Range Lower and Upper Bound Seed Data
biobankinguk/biobankinguk pull request #165
Opened 2021-03-25 11:20 UTC by JosephLavagna

- Added new lower and upper bound data to seed data .json

2021-03-25 11:29 UTC, Flemingjp approved these changes

2021-03-25 11:32 UTC, blargly requested changes

2021-03-25 11:32 UTC, blargly commented on sample-seed-data/AgeRange.json
> +        "lowerBound": "0M",
As these are durations, shouldn't they begin with a P as a designator?
https://en.wikipedia.org/wiki/ISO_8601#Durations

2021-03-25 11:32 UTC, beforan commented on sample-seed-data/AgeRange.json
> +        "upperBound": "0"
are we intending to support a naked `0` value? or should it still be a valid duration (in which case `P0D` or similar would be better`?

> Date and time elements including their designator may be omitted if their value is zero, and lower-order elements may also be omitted for reduced precision. For example, "P23DT23H" and "P4Y" are both acceptable duration representations. However, at least one element must be present, thus "P" is not a valid representation for a duration of 0 seconds. "PT0S" or "P0D", however, are both valid and represent the same duration.

2021-03-25 11:33 UTC, beforan commented on sample-seed-data/AgeRange.json
> +        "lowerBound": "0M",
good catch!

2021-03-25 13:39 UTC, Flemingjp approved these changes

2021-03-25 13:55 UTC, beforan requested changes

2021-03-25 13:55 UTC, beforan commented on sample-seed-data/AgeRange.json
> +        "lowerBound": "P-1Y",
aha, this one is an oddity.

Some details covered in [this issue](https://github.com/moment/moment/issues/2408), but the upshot is:
- ISO 8601 never actually specifically allows negative durations
- .NET's `XmlConvert` (which is likely to be our implementation) uses the related `xs:duration` XML standard which does allow the WHOLE duration to be negative. i.e. `-P1D` not `P-1D`.
- so we should use that approach for negative :)

2021-03-26 10:36 UTC, Flemingjp approved these changes

2021-03-29 14:19 UTC, beforan approved these changes

2021-03-30 07:54 UTC, blargly approved these changes

2021-03-30 07:55 UTC, merged