AB#32511: Age ranges UI changes
biobankinguk/biobankinguk pull request #172
Opened 2021-04-07 16:26 UTC by JosephLavagna

- Added lower and upper bounds to age ranges
- Stores them in db ISO duration format - e.g 6 months: P6M
- Displayed in UI in 'plain text' format not ISO duration
- Checks if upper bound is higher than lower bound

2021-04-08 08:00 UTC, beforan requested changes

2021-04-08 08:24 UTC, beforan approved these changes

2021-04-09 10:13 UTC, Flemingjp submitted a review, later dismissed

2021-04-09 10:19 UTC, beforan requested changes

2021-04-09 10:19 UTC, beforan commented on src/Directory/Services/BiobankReadService.cs
> +        public async Task<bool> ValidAgeRangeAsync(int ageRangeId, string ageRangeDescription)
I think this is a misleading method name. Really it checks `IsAgeRangeDescriptionInUse` I think?

The `InUse` bit is key, otherwise checking for a non matching `Id` is quite confusing!

2021-04-09 10:19 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/AgeRangeController.cs
> +                ModelState.AddModelError("AgeRange", "Both Upper and Lower Bounds must not be null.");
What about the default entry, where both were null to begin with?

2021-04-09 10:19 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/AgeRangeController.cs
> +                ModelState.AddModelError("AgeRange", "Both Upper and Lower Bounds must not be null.");
(and cannot be changed in the UI)

2021-04-09 10:24 UTC, JosephLavagna commented on src/Directory/Services/BiobankReadService.cs
> +        public async Task<bool> ValidAgeRangeAsync(int ageRangeId, string ageRangeDescription)
Wasn't too sure about this - went off other similar methods i.e - 
`        public async Task<bool> ValidConsentRestrictionDescriptionAsync(int consentId, string consentDescription)
            => (await _collectionConsentRestrictionRepository.ListAsync(
                false,
                x => x.Value == consentDescription &&
                     x.Id != consentId)).Any();`

2021-04-13 10:54 UTC, beforan approved these changes

2021-04-14 13:28 UTC, merged