AB#32465: Bulk Submissions Settings View
biobankinguk/biobankinguk pull request #174
Opened 2021-04-07 17:58 UTC by shakisparki

## Overview

Add Biobank Bulk Submissions Settings View

2021-04-15 13:36 UTC, beforan submitted a review, later dismissed
I messed up and blocked the wrong PR.

This PR blocks #188 until its merged

2021-04-15 13:40 UTC, beforan commented
@shakisparki are migrations resolved yet after #187 merge?

2021-04-15 13:41 UTC, shakisparki commented
> @shakisparki are migrations resolved yet after #187 merge?

Yes, all resolved for this PR

2021-04-19 14:59 UTC, Flemingjp requested changes
- Missing an entry for the `Mvc.sitemap`, this means the navigation bar is missing on the page

2021-04-19 14:59 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Views/Biobank/Submissions.cshtml
> +    found here (todo link).
(todo link)

2021-04-19 14:59 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Views/Biobank/Submissions.cshtml
> +                @Html.DisplayNameFor(x => x.CollectionType)
Appears to be a required field - needs the required class

2021-04-19 14:59 UTC, Flemingjp commented on src/Entities/Data/Organisation.cs
> +
Current convention is to have a ID field for the FK - `AccessConditionId` for example. Very few entities uses the DataAnnotations.

Am I correct in my thinking @blargly?

2021-04-19 15:20 UTC, Flemingjp commented on src/Entities/Data/Organisation.cs
> +
Unless the Ids are used - they can be dropped, along with the ForeignKey annotation. EF should be able to populate `AccessConition` and `CollectionType` from the type alone

2021-04-20 09:24 UTC, blargly approved these changes

2021-04-20 09:25 UTC, blargly submitted a review, later dismissed

2021-04-21 08:31 UTC, beforan commented on src/Directory/Biobanks.Web/Views/Biobank/Submissions.cshtml
> +    found here (todo link).
if the a link is available (I suspect not) then obvs add it.

If not then:
- I'm ok with this `<p>` being commented out, with a `TODO` in the comments.
- Create a work item in DevOps for getting the link and adding it to the view
- The `TODO` should reference the work item ID

2021-04-21 08:34 UTC, beforan reviewed
just clearing my previous changes requested so I'm not a blocker ;)

2021-04-21 15:31 UTC, closed without merging