AB#29896: Generate Aggregated Collections
biobankinguk/biobankinguk pull request #191
Opened 2021-04-20 10:30 UTC by Flemingjp

2021-04-21 08:39 UTC, beforan requested changes

2021-04-21 08:39 UTC, beforan commented on src/Aggregator/AzFunctions/Functions/AggregatorFunction.cs
> +            if (dirtySamples.Any())
This sort of structural logic isn't Azure Functions specific, is it?

It should be further abstracted, so it could be called from a console app, or aws lambda, or whatever.

The platform specific bit really should be as thin as possible, while the common bit should be as much as possible to ensure standardised behaviour across platforms

2021-04-21 08:51 UTC, Flemingjp commented on src/Aggregator/AzFunctions/Functions/AggregatorFunction.cs
> +            if (dirtySamples.Any())
Yeah was considering the best way to further abstract this. It should be straight-forward as the function doesn't require any parameters passed to it. Just not sure what the best way to abstract this block of code - something equivalent to Java's `Task`?

2021-04-22 08:44 UTC, Flemingjp commented on src/Aggregator/AzFunctions/Functions/AggregatorFunction.cs
> +            if (dirtySamples.Any())
Solution was to move the logic to `AggregationTask` which is just a class with a `Run` function. Nothing special but seemed the simplest way to abstract while remaining clear

2021-04-30 09:12 UTC, Flemingjp commented on src/Aggregator/Core/Services/AggregationService.cs
> +            => await _db.MaterialDetails.Where(x => x.SampleSetId == id).DeleteAsync();
Should be in a MaterialDetails service on its own?

2021-04-30 09:13 UTC, Flemingjp commented on src/Aggregator/Core/Services/CollectionService.cs
> +        }
Change to DeleteById method? Also SaveChangesAsync isnt needed with DeleteAsync(), so will be removed

2021-04-30 09:14 UTC, Flemingjp commented on src/Data/BiobanksDbContext.cs
> +
No longer needed with manual cascade delete implemented?

2021-04-30 09:15 UTC, Flemingjp commented on src/Aggregator/Core/AggregationTask.cs
> +                            await _aggregationService.DeleteMaterialDetailsBySampleSetId(ss);
Thoughts on a `_materialDetailsService.DeleteBySampleSetIds(IEnumerable<int> ids)` method instead?

2021-04-30 09:16 UTC, Flemingjp commented on src/Aggregator/Core/AggregationTask.cs
> +                            await _sampleService.DeleteSampleSetById(ss);
Same idea on multiple id delete service method

2021-05-05 13:39 UTC, beforan commented on src/Aggregator/Core/AggregationTask.cs
> +                            await _aggregationService.DeleteMaterialDetailsBySampleSetId(ss);
not really fussed, all it's doing is moving where the foreach loop is, and since this is already shared code, not implementation specific, i'm not too fussed.

2021-05-05 13:40 UTC, beforan commented on src/Aggregator/Core/AggregationTask.cs
> +                            await _sampleService.DeleteSampleSetById(ss);
same response :P

2021-05-05 13:40 UTC, beforan commented on src/Data/BiobanksDbContext.cs
> +
seems legit. try removing it and see if it requires a migration though...

2021-05-05 13:40 UTC, beforan commented on src/Aggregator/Core/Services/CollectionService.cs
> +        }
hold the 📞 why isn't SaveChanges required after Delete?

2021-05-05 13:41 UTC, beforan commented on src/Aggregator/Core/Services/AggregationService.cs
> +            => await _db.MaterialDetails.Where(x => x.SampleSetId == id).DeleteAsync();
arguably, but probably not if it's gonna be a service with one one line method?

2021-05-05 13:44 UTC, beforan commented on src/Aggregator/AzFunctions/Startup.cs
> +                .EnableSensitiveDataLogging()
what's this?

2021-05-05 13:44 UTC, beforan commented on src/Aggregator/AzFunctions/Startup.cs
> +                ServiceLifetime.Transient
do we need to specify this?

2021-05-05 14:45 UTC, Flemingjp commented on src/Data/BiobanksDbContext.cs
> +
Checked - no migration needed

2021-05-05 14:46 UTC, Flemingjp commented on src/Aggregator/AzFunctions/Startup.cs
> +                ServiceLifetime.Transient
Not sure - was taken from [https://github.com/biobankinguk/biobankinguk/blob/0e4bc7e94353f3bb5996902a14c5fdaaa26c53b4/src/Submissions/AzFunctions/Startup.cs#L48](Submission AzFunction)

2021-05-05 14:47 UTC, Flemingjp commented on src/Aggregator/AzFunctions/Startup.cs
> +                .EnableSensitiveDataLogging()
Same as comment below

2021-05-05 14:50 UTC, Flemingjp commented on src/Aggregator/Core/Services/CollectionService.cs
> +        }
`DeleteAsync` is from `Z.EntityFramework.Plus` and works without `SaveChangesAsync()`. A good existing example is in `SampleService`

https://github.com/biobankinguk/biobankinguk/blob/821a96c01732f80fbea73c1cc71e23ef74079466/src/Aggregator/Core/Services/SampleService.cs#L41-L42

2021-05-06 08:49 UTC, beforan commented on src/Aggregator/Core/Services/CollectionService.cs
> +        }
noice

2021-05-06 08:49 UTC, beforan commented on src/Aggregator/AzFunctions/Startup.cs
> +                ServiceLifetime.Transient
can now confirm we don't need this, it's lineage dates back to the old submissions webjob.

2021-05-06 08:49 UTC, beforan commented on src/Aggregator/AzFunctions/Startup.cs
> +                .EnableSensitiveDataLogging()
can now confirm we don't need this, it's lineage dates back to the old submissions webjob.

2021-05-06 09:33 UTC, beforan approved these changes

2021-05-06 10:01 UTC, beforan requested changes

2021-05-06 10:01 UTC, beforan commented on src/Aggregator/Core/Services/Contracts/ICollectionService.cs
> +        Task DeleteCollectionAsync(Collection collection);
remove `Async` suffix pls.

2021-05-06 10:06 UTC, beforan approved these changes

2021-05-06 11:02 UTC, blargly approved these changes

2021-05-06 11:03 UTC, merged