AB#30988: Add preservation type to material details
biobankinguk/biobankinguk pull request #199
Opened 2021-04-23 17:32 UTC by bradthompson995

## Overview

Adding functionality to perservation type to the material details for sample sets.

2021-04-30 12:34 UTC, Flemingjp requested changes

2021-04-30 12:34 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/StorageTemperatureController.cs
> +        {
Can just do `=> await ()`

2021-04-30 12:34 UTC, Flemingjp commented on src/Directory/Data/Configs/ConfigKey.cs
> +        public const string StorageTemperatureName = "site.display.storagetemperature.name"; //TODO: Migrate key name?
This is fine - but will need updating on existing environments

2021-04-30 12:34 UTC, Flemingjp commented on src/Directory/Services/BiobankReadService.cs
Can do `await _materialDetailsRepository.CountAsync(x => x.PreservationTypeId == id)` instead

2021-05-06 07:07 UTC, Flemingjp approved these changes

2021-05-06 07:25 UTC, beforan approved these changes

2021-05-06 07:25 UTC, merged