Upgrade Publications Service
biobankinguk/biobankinguk pull request #213
Opened 2021-04-29 17:02 UTC by shakisparki

## Overview

Upgrade Publication class library and azure function to .NET 5

2021-04-29 17:36 UTC, shakisparki commented on src/Publications/PublicationsAzFunctions/Functions/BatchFunction.cs
>              await _fetchAnnotationsService.StartAsync(cancellationToken);
I believe cancellationTokens are not supported in .NET 5? should we leave this as a hosted service?

2021-04-29 17:37 UTC, shakisparki commented on src/Publications/PublicationsAzFunctions/Startup.cs
> +            services.AddTransient<FetchPublicationsService>();
Should these be AddTransient or AddHostedService?

2021-04-30 08:33 UTC, beforan requested changes

2021-04-30 08:33 UTC, beforan commented on src/Publications/PublicationsAzFunctions/PublicationsAzFunctions.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
this project should just be called `AzFunctions`

2021-04-30 08:33 UTC, beforan commented on src/Publications/PublicationsAzFunctions/Functions/BatchFunction.cs
>              await _fetchAnnotationsService.StartAsync(cancellationToken);
why was it a hosted service to begin with? it's not run as one. I don't believe it should be one.

You would use a hosted service in a console app to provide the equivalent wrapper to what the Azure Function class and method are doing.

2021-04-30 08:33 UTC, beforan commented on src/Publications/PublicationsAzFunctions/PublicationsAzFunctions.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
Get rid of this `.sln`. The whole Publications Service only needs one Solution at its top level - as per Submissions.

2021-04-30 08:33 UTC, beforan commented on src/Publications/PublicationsAzFunctions/Startup.cs
> +            services.AddTransient<FetchPublicationsService>();
Transient

2021-04-30 08:33 UTC, beforan commented on src/Publications/Publications/Services/PublicationService.cs
> +        private BiobanksDbContext _ctx;
call this `_db` to match all other projects / context usage

2021-04-30 08:33 UTC, beforan commented on src/Publications/Publications/Services/Hosted/FetchPublicationsService.cs
>      public class FetchPublicationsService : IHostedService
As discussed, no need for this to implement IHostedService

2021-04-30 08:33 UTC, beforan commented on src/Publications/Publications/Services/Hosted/FetchAnnotationsService.cs
>      public class FetchAnnotationsService : IHostedService
This probably also shouldn't be IHostedService?

2021-04-30 08:33 UTC, beforan commented on src/Publications/Publications/Services/BiobankReadService.cs
> +        private BiobanksDbContext _ctx;
`_db` for consistency

2021-04-30 08:33 UTC, beforan commented on src/Publications/Publications/Services/AnnotationService.cs
> +        private BiobanksDbContext _ctx;
`_db` for consistency

2021-04-30 08:33 UTC, beforan commented on src/Publications/Publications/Publications.csproj
> +    <PackageReference Include="MatthiWare.CommandLineParser" Version="0.6.0" />
What is this dependency for? Get rid of it if it's not used, or if it used we should consider replacing it with the same libraries we use elsewhere for command line parsing, for consistency (`System.CommandLine`)

2021-04-30 08:33 UTC, beforan commented on src/Publications/Publications/Publications.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.5">
I don't believe this project needs granular EF Core dependencies.

In part because it doesn't run migrations anymore.

Refer to Submissions and see if you can pare this down similarly.

e.g. `Submissions.Core` doesn't even depend on EF Core, because it depends on `Biobanks.Data`, which does.

2021-04-30 08:33 UTC, beforan commented on src/Publications/Publications/Publications.csproj
> +    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="5.0.0" />
I doubt this class library needs hosting abstractions? check and confirm.

2021-04-30 08:33 UTC, beforan commented on src/Publications/Publications/Publications.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
If this is the shared class library project, it should be called `Core`. Refer to Submissions and follow that pattern.

2021-04-30 08:33 UTC, beforan commented on src/Publications/Publications/Publications.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
Do we use Newtonsoft? If so, do we need to or can we use `System.Text.Json` instead? Most (all?) of our new (.NET Core/5+) apps use it now, so it would be nice to be consistent unless we need specific Newtonsoft features.

2021-04-30 08:36 UTC, beforan commented
Build workflow needs fixing. The build job in the Release workflow will also need changes. As ever, copy Submissions

2021-04-30 08:36 UTC, Flemingjp requested changes
Just gitignore change - not sure of the answers to your questions

2021-04-30 08:36 UTC, Flemingjp commented on src/Publications/PublicationsAzFunctions/.gitignore
Shouldnt we ignore local files?

2021-05-04 16:55 UTC, Flemingjp submitted a review, later dismissed

2021-05-05 13:36 UTC, beforan approved these changes

2021-05-05 13:43 UTC, JosephLavagna approved these changes

2021-05-05 13:46 UTC, beforan requested changes

2021-05-05 13:46 UTC, beforan commented on .github/workflows/build.publications.yml
>      branches: [main]
`main.release.yml` workflow needs changing as well, to build analytics as .net 5.0

2021-05-05 13:59 UTC, beforan approved these changes

2021-05-05 14:00 UTC, Flemingjp approved these changes

2021-05-05 14:00 UTC, merged