AB#32271: Analytics update
biobankinguk/biobankinguk pull request #214
Opened 2021-05-04 09:25 UTC by blargly

Analytics has had some consolidation in line with the submissions solution.

- unique context has been removed
- projects are now .NET 5
- entities added to both remaining contexts
- entities now covered by migrations
- hosted services removed

2021-05-04 09:50 UTC, Flemingjp requested changes

2021-05-04 09:50 UTC, Flemingjp commented on src/Analytics/Services/BiobankWebService.cs
> +            _context = context;
`_db` instead? Just to keep it consistent across the codebase

2021-05-05 09:05 UTC, beforan requested changes

2021-05-05 09:05 UTC, beforan commented on src/Analytics/AzureFunctions/BatchFunction.cs
> +        public async Task Run([TimerTrigger("0 0 0 1 */3 *", RunOnStartup = false)] ILogger log) //remove runonstartup before deploying
`TimerInfo myTimer` is still needed...

You may need to add the types for this, either from a nuget pakcage or manually like the other functions have done.

(it would be good to switch to the nuget package, but all the others also need fixing so that can be a specific PBI i guess...)

2021-05-05 09:05 UTC, beforan commented on src/Analytics/AzureFunctions/Startup.cs
> +            services.AddMemoryCache();
does analytics use this? it didn't before...

2021-05-05 09:05 UTC, beforan commented on src/Analytics/AzureFunctions/Startup.cs
> -            builder.Services.AddHttpClient();
is this no longer needed?

2021-05-05 09:05 UTC, beforan commented on src/Analytics/Services/BiobankWebService.cs
> +        public BiobankWebService(BiobanksDbContext context)
can we rename this service? it's no longer a web service as it hits the db directly rather than making api calls.

honestly should probably just be `BiobankReadService`?

2021-05-05 09:05 UTC, beforan commented on src/Analytics/Services/GoogleAnalyticsReadService.cs
> +        private readonly BiobanksDbContext _context;
`_db`

2021-05-05 09:05 UTC, beforan commented on src/Directory/Services/BiobankReadService.cs
> +                var x = e.Message;
remove this debugging stuff?

2021-05-05 11:54 UTC, blargly commented on src/Analytics/Services/BiobankWebService.cs
> +            _context = context;
Changed

2021-05-05 11:55 UTC, blargly commented on src/Analytics/Analytics/Data.csproj
> +    <TargetFramework>net5.0</TargetFramework>
Removed as part of rename cleanup earlier

2021-05-05 11:56 UTC, blargly commented on src/Analytics/Services/GoogleAnalyticsReadService.cs
> +        private readonly BiobanksDbContext _context;
Renamed

2021-05-05 11:58 UTC, blargly commented on src/Directory/Services/BiobankReadService.cs
> +                var x = e.Message;
My bad, removed.

2021-05-05 12:07 UTC, blargly commented on src/Analytics/Services/BiobankWebService.cs
> +        public BiobankWebService(BiobanksDbContext context)
Done

2021-05-05 12:25 UTC, blargly commented on src/Analytics/AzureFunctions/BatchFunction.cs
> +        public async Task Run([TimerTrigger("0 0 0 1 */3 *", RunOnStartup = false)] ILogger log) //remove runonstartup before deploying
Why is it still needed? I can't see it being used. Restored for now, as its used in all of the examples, but I'm not clear on its role.

2021-05-05 13:50 UTC, beforan commented on src/Analytics/AzFunctions/Startup.cs
> +                .EnableSensitiveDataLogging()
why?

2021-05-05 13:50 UTC, beforan commented on src/Analytics/AzFunctions/Startup.cs
> +                ServiceLifetime.Transient
do we need this? (we don't normally)

2021-05-06 07:58 UTC, blargly commented on src/Analytics/AzFunctions/Startup.cs
> +                ServiceLifetime.Transient
(we do in submissions, which this is modelled on)

2021-05-06 08:04 UTC, blargly commented on src/Analytics/AzFunctions/Startup.cs
> +                ServiceLifetime.Transient
Also publications PR 213 has this exact same change which you approved :D

2021-05-06 08:48 UTC, beforan commented on src/Analytics/AzFunctions/Startup.cs
> +                ServiceLifetime.Transient
i'm only human 🤭 can now confirm we don't need this, it's lineage dates back to the old submissions webjob.

2021-05-06 08:49 UTC, beforan commented on src/Analytics/AzFunctions/Startup.cs
> +                .EnableSensitiveDataLogging()
we should remove this, it came almost virally from the old submissions webjob

2021-05-06 09:34 UTC, beforan approved these changes

2021-05-06 09:36 UTC, Flemingjp approved these changes

2021-05-06 09:36 UTC, merged