AB#34026: CRUD Methods for ContentPages
biobankinguk/biobankinguk pull request #215
Opened 2021-05-04 09:30 UTC by thomasread99

## Overview

Added the CRUD functionality to the ContentPages in a ContentPageService

2021-05-04 09:45 UTC, Flemingjp requested changes

2021-05-04 09:45 UTC, Flemingjp commented on src/Data/Migrations/20210427112114_CreateContentPage.cs
> +                    LastUpdated = table.Column<DateTime>(type: "datetime2", nullable: false),
Doesn't this migration already exist earlier?

2021-05-04 09:45 UTC, Flemingjp commented on src/Directory/Services/ContentPageService.cs
> +        }
Is this all required here? Currently it is taken from the IGenericRepository pattern, but for example the `includeProperties` could be omitted as the ContentPage entity doesn't have an Foreign Keys - would also be tempted not to required `orderBy`?

2021-05-04 09:45 UTC, Flemingjp commented on src/Directory/Services/Contracts/IContentPageService.cs
> +        Task<ContentPage> GetById(object id);
`id` can be `int`

2021-05-04 09:45 UTC, Flemingjp commented on src/Directory/Services/Contracts/IContentPageService.cs
> +        Task<ContentPage> GetBySlug(object routeSlug);
`routeSlug` can be `string`

2021-05-04 09:49 UTC, thomasread99 commented on src/Data/Migrations/20210427112114_CreateContentPage.cs
> +                    LastUpdated = table.Column<DateTime>(type: "datetime2", nullable: false),
I am pretty sure the migration was created with the last task & pull request I did last week

2021-05-04 09:52 UTC, Flemingjp commented on src/Data/Migrations/20210427112114_CreateContentPage.cs
> +                    LastUpdated = table.Column<DateTime>(type: "datetime2", nullable: false),
Ah yes, this issue is because of #206. If you remove this migration from your branch using `dotnet ef migrations remove` and then merge `main` into this branch, it should resolve the issue.

2021-05-04 09:57 UTC, Flemingjp requested changes

2021-05-04 09:57 UTC, Flemingjp commented on src/Directory/Services/ContentPageService.cs
> +        }
This can now be condensed nicely

```c#
return filter == null
  ? query.ToList()
  : query.Where(filter).ToList();
```

2021-05-04 10:14 UTC, thomasread99 commented on src/Data/Migrations/20210427112114_CreateContentPage.cs
> +                    LastUpdated = table.Column<DateTime>(type: "datetime2", nullable: false),
Think that's been done now, had a few merge conflicts but hopefully it's okay!

2021-05-04 12:31 UTC, Flemingjp submitted a review, later dismissed

2021-05-05 09:36 UTC, beforan requested changes

2021-05-05 09:36 UTC, beforan commented on src/Directory/Services/ContentPageService.cs
> +            return await _db.ContentPages.FindAsync(routeSlug);
this isn't how `FindAsync()` works. it only looks for the primary key.

so to find by slug you'll need to do `_db.ContentPages.FirstOrDefault(x -> x.Slug == routeSlug)`

2021-05-05 09:36 UTC, beforan commented on src/Directory/Services/ContentPageService.cs
> +            if (_db.Entry(contentPage).State == EntityState.Detached)
i don't think this detached check is terribly useful.

Also, this method needs to `SaveChanges` after removing the entity.

In practice, as well, I don't think we'll ever have the entity when we ask the service to delete; it's much mroe likely we'll have the `Id` only.

(This is a side effect of designing this feature from the bottom up; we hadn't planned out the UI when work on this service started).

So can we change this to take an id parameter, then the method gets the entity by id (`FindAsync`) and if it finds nothing, just return (that's as good as deleted) or if it finds something, then `Remove` it and `SaveChangesAsync`.

2021-05-05 09:36 UTC, beforan commented on src/Directory/Services/ContentPageService.cs
> +        public IEnumerable<ContentPage> ListContentPages(bool tracking = false,
get rid of the arguments here.

This should just list all pages, untracked.

I was only using the repository as an example of how NOT to do `Update()`, not that this service should try and be a repository :)

2021-05-05 09:36 UTC, beforan commented on src/Directory/Services/ContentPageService.cs
> +        public void UpdateContentPage(ContentPage contentPage)
This method is basically useless.

we shouldn't need to manage tracking ourselves. It's more likely the Controller will pass either its ViewModel, or a Data Transfer Object, from which we should map its properties onto our existing Entity, then `SaveChanges`.

Actually, this is pretty hard to do without the controller side model. Unless we take params, which we could for now since ContentPage is pretty lightweight.

So switch the params to `Id, Title, Body, Slug`.

Then get the existing entity by `FindAsync()` using the Id.

If you find nothing, throw a `KeyNotFoundException`.

If you find something, set its properties to the parameters:
- Title,
- Slug,
- Body
and set `LastUpdated` to todays Date/Time in UTC: `DateTime.UtcNow` or `DateTimeOffset.UtcNow` depending what the entity uses (I can't remember).

then `SaveChangesAsync()`

2021-05-05 09:36 UTC, beforan commented on src/Directory/Services/Contracts/IContentPageService.cs
> +        Task CreateNewContentPage(ContentPage contentPage);
change these method names. it's a `ContentPageService` so `Create` is fine

2021-05-05 09:36 UTC, beforan commented on src/Directory/Services/ContentPageService.cs
> +        public async Task CreateNewContentPage(ContentPage contentPage)
it would be better for this to take a model, or parameters.

Saves the calling code knowing what the Entity looks like.

So switch the params to `Title, Body, Slug`.

the initialise a new `ContentPage` entity, and set those properties on it.
and set LastUpdated to todays Date/Time in UTC.

than add that new Entity, and `SaveChangesAsync`

2021-05-11 08:32 UTC, Flemingjp requested changes

2021-05-11 08:32 UTC, Flemingjp commented on src/Directory/Services/ContentPageService.cs
> +
One nice thing you can do here

```c#
var page = new ContentPage
{
  Title = title,
  Body = body,
  RouteSlug = slug,
  LastUpdated = DateTime.UtcNow
};
```

2021-05-11 08:32 UTC, Flemingjp commented on src/Directory/Services/ContentPageService.cs
> +            if (page == null)
We can inverse the null check, if the null condition does nothing

```c#
if (page != null)
{
  _db.ContentPages.Remove(page);
  await _db.SaveChangesAsync();
}
```

2021-05-11 08:32 UTC, Flemingjp commented on src/Directory/Services/ContentPageService.cs
> +                return;
Can remove the return statement - it will return at the end of the method anyways

2021-05-11 08:32 UTC, Flemingjp commented on src/Directory/Services/ContentPageService.cs
> +                throw new KeyNotFoundException();
Might be no need to throw an error here? Not sure what the convention should be @beforan

2021-05-11 08:32 UTC, Flemingjp commented on src/Directory/Services/ContentPageService.cs
> +            return await _db.ContentPages.FindAsync(id);
More a stylistic comment - but single lines can be inlined  `=> await _db.ContentPages.FindAsync(id);`

2021-05-11 08:32 UTC, Flemingjp commented on src/Directory/Services/ContentPageService.cs
> +            return await _db.ContentPages.FirstOrDefaultAsync(x => x.RouteSlug == routeSlug);
Same here `=> await _db.ContentPages.FirstOrDefaultAsync(x => x.RouteSlug == routeSlug);`

2021-05-11 08:32 UTC, Flemingjp commented on src/Directory/Services/ContentPageService.cs
> +        {
Change to Async method and can be condensed `=> _db.ContentPages.ToListAsync()`

2021-05-11 09:31 UTC, thomasread99 commented on src/Directory/Services/ContentPageService.cs
> +        {
Was not able to condense this one - I think to do with datatypes etc but let me know if there's something I have missed!

2021-05-11 10:03 UTC, Flemingjp requested changes

2021-05-11 12:22 UTC, merged