AB#34505: Support Non-Extracted Samples In The Aggregator
biobankinguk/biobankinguk pull request #218
Opened 2021-05-06 13:18 UTC by Flemingjp

In draft

2021-07-27 08:06 UTC, beforan requested changes

2021-07-27 08:06 UTC, beforan commented on src/Core/Aggregator/Services/OrganisationService.cs
> +namespace Biobanks.Aggregator.Core.Services
There is already a Shared OrganisationService in Core. please use / augment it :)

2021-07-27 08:26 UTC, Flemingjp commented on src/Core/Aggregator/Constants/OntologyTerms.cs
> +        public const string FitAndWell = "102499006";
Yeah I agree environmental variables is probably the best way forward - same with the MacroscopicAssessments

2021-07-29 11:23 UTC, beforan requested changes

2021-07-29 11:23 UTC, beforan commented on src/Core/Aggregator/AggregatorOptions.cs
> +                MacroscopicAssessmentMappings.First(x => string.IsNullOrEmpty(x.ContentMethod) && string.IsNullOrEmpty(x.ContentId));
is this guaranteed to find something? or should it be `FirstOrDefault()` for the last one too?

because your reutrn value null coalesces map, suggesting it can be null after assignment.

2021-07-29 11:23 UTC, beforan commented on src/Submissions/Api/Startup.cs
> +            var aggregatorConfig = Configuration.GetSection("Aggregator").Get<AggregatorOptions>();
you only need this assignent if you need to use the config inside `ConfigureServices()`.

it doesn't look like you do, so the `.Configure<T>()` call below is enough.

Honestly it's a bit annoying the others have to be in both places, but you can't use the registered service version (that `.Configure<T>()` does) until the serice provider is built, which happens after `ConfigureServices()` completes.

2021-07-29 11:23 UTC, beforan commented on src/Submissions/Api/appsettings.json
> +    "MacroscopicAssessmentMappings": [
is it appropriate for these to be default configurations? or should they always be environment specific.

They won't work without matching ref data, right?

2021-07-29 11:27 UTC, Flemingjp commented on src/Core/Aggregator/AggregatorOptions.cs
> +                MacroscopicAssessmentMappings.First(x => string.IsNullOrEmpty(x.ContentMethod) && string.IsNullOrEmpty(x.ContentId));
This depends how we want to handle no mapping. Do we throw and log this as an error, or do we allow a null macroscopic assessment to go through? Is it valid for a MaterialDetail to have a null MacroscopicAssessment

2021-07-29 12:33 UTC, Flemingjp commented on src/Core/Aggregator/AggregatorOptions.cs
> +                MacroscopicAssessmentMappings.First(x => string.IsNullOrEmpty(x.ContentMethod) && string.IsNullOrEmpty(x.ContentId));
This method now return null when no valid mapping. However where it is used will still throw an error, as MacroscopicAssessment is a required field. We should figure out how we handle such errors

2021-08-12 07:40 UTC, beforan approved these changes

2021-08-12 07:54 UTC, blargly approved these changes

2021-08-12 07:54 UTC, merged