Publications Job
biobankinguk/biobankinguk pull request #226
Opened 2021-05-11 12:23 UTC by Flemingjp

##Draft PR
Moves the Publications Azure Function to the new Core project and abstracts the function to a Jobs class with a single `Run()` method.

Publication Job is then scheduled via Hangfire in the Submissions API

2021-05-11 12:24 UTC, Flemingjp commented on src/Submissions/Api/Startup.cs
> +            RecurringJob.AddOrUpdate<PublicationsJob>("job-publications", x => x.Run(), Cron.Daily);
Is this the best place to define these jobs?

2021-05-11 12:32 UTC, beforan commented on src/Submissions/Api/Startup.cs
> +            RecurringJob.AddOrUpdate<PublicationsJob>("job-publications", x => x.Run(), Cron.Daily);
i say "them all" when obvs that doesn't apply to this PR, but we know there will be other recurring jobs in future

2021-05-11 15:12 UTC, beforan requested changes

2021-05-11 15:32 UTC, beforan commented on src/Core/Shared/Services/BiobankReadService.cs
> +        public async Task<IList<Organisation>> ListBiobanksAsync(string wildcard = "",
yeah we should

2021-05-12 08:34 UTC, beforan approved these changes

2021-05-12 08:41 UTC, blargly approved these changes

2021-05-12 08:41 UTC, merged