AB#32820: Honeypot Registration forms
biobankinguk/biobankinguk pull request #227
Opened 2021-05-11 16:47 UTC by shakisparki

## Overview

Adds a hidden honey pot field.
If set to true during registration, User is added to the block list.

### Note
PR branches off of `blockallowEmailDomain` branch work in progress by @bradthompson995 

### To Do

- [ ] Add bool Honey pot field to model
- [ ] Add functionality for Biobank Registration
- [ ] Add checkbox input to shared partial view 
- [ ] Add functionality for Network Registration
- [ ] Add JavaScript for checkbox

2021-05-13 08:36 UTC, Flemingjp requested changes

2021-05-13 08:36 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Controllers/ADACController.cs
> +
Can we remove the additional blank lines?

2021-05-13 08:36 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Controllers/RegisterController.cs
> +        {
Is `internal` required here?

2021-05-13 08:36 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationDomainRuleController.cs
> +            var model = (await _biobankReadService.ListRegistrationDomainRulesAsync())
Might as well have it as a single return statement here.

2021-05-13 08:36 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationDomainRuleController.cs
> +        public async Task<IList> Get()
Is `IList` used over `IEnumerable` to ensure Json payload here?

2021-05-13 08:36 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationDomainRuleController.cs
> +            });
Do we need to have a success variable here - a HTTP 200 OK should be sufficient? @beforan?

2021-05-13 13:25 UTC, shakisparki commented on src/Directory/Biobanks.Web/Controllers/ADACController.cs
> +
These snippets are from Bradley's PR. Code for this PR should be more visible once he's merged his work.

2021-05-13 13:43 UTC, shakisparki commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationDomainRuleController.cs
> +            var model = (await _biobankReadService.ListRegistrationDomainRulesAsync())
These snippets are from Bradley's PR

2021-05-13 13:43 UTC, shakisparki commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationDomainRuleController.cs
> +        public async Task<IList> Get()
These snippets are from Bradley's PR

2021-05-13 13:43 UTC, shakisparki commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationDomainRuleController.cs
> +            });
These snippets are from Bradley's PR

2021-05-18 14:15 UTC, Flemingjp approved these changes

2021-05-19 08:19 UTC, blargly approved these changes

2021-05-19 08:28 UTC, merged