AB#35078: Submission hangfire implementation
biobankinguk/biobankinguk pull request #232
Opened 2021-05-13 15:17 UTC by blargly

In draft - do not merge yet.

2021-05-13 15:23 UTC, blargly commented
Still need to sort out the configuration bits which set it to use hangfire.

Also needs ISubmissionService rolling back, as I made many of the methods private not realising they're used elsewhere.  maybe it needs to be split up> Old function logic could go in its own service, though not sure its warranted

2021-05-14 15:27 UTC, beforan requested changes
Also need to delete/modify some CI bits:

- labeler configuration
- Submissions AzFunctions build workflow
- Submissions AzFunctions artifact bits inside `main.release.yml`

you should be able to mostly bae these changes on the equivalent ones in #234 or #235 or #228

2021-05-14 15:27 UTC, beforan commented on src/Core/Submissions/Services/SubmissionService.cs
> +
lots of constructor injection needed?

2021-05-17 11:08 UTC, Flemingjp reviewed
Will approve once outstanding comments are resolved

2021-05-19 08:17 UTC, Flemingjp approved these changes

2021-05-19 08:32 UTC, beforan requested changes

2021-05-19 08:32 UTC, beforan commented on .github/labeler.yml
> +  - src/Core/Jobs/RejectJob.cs
what about staging?

2021-05-19 08:41 UTC, beforan approved these changes

2021-05-19 08:54 UTC, Flemingjp approved these changes

2021-05-19 08:55 UTC, merged