AB#33736: Blocklist/AllowList email domain
biobankinguk/biobankinguk pull request #236
Opened 2021-05-14 11:02 UTC by bradthompson995

## Overview

Implementing ADAC functionality to allow ADAC users to add rules to allow or block specific email domains via the Email Config ADAC page 

Rules which are added via the implemented ADAC CRUD UI are assigned a source of ADAC. 

The ADAC registration process for Biobanks & Networks ignores this implemented fucntionality.

Domains which are covered by an Allow rule can override any Block rule which would also apply to them.

2021-05-14 12:05 UTC, Flemingjp requested changes

2021-05-14 12:05 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationDomainRuleController.cs
> +            if (!ModelState.IsValid)
Just a few empty lines that can be cleaned up

2021-05-14 12:05 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationDomainRuleController.cs
> +            var model = (await _biobankReadService.ListRegistrationDomainRulesAsync()).First(x => x.Id == id);
`FirstOrDefault()` followed by a null check?

2021-05-14 12:05 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Controllers/ADACController.cs
> +
Remove blank lines

2021-05-14 12:05 UTC, Flemingjp commented on src/Directory/Services/BiobankWriteService.cs
> +        }
As a new set of service methods this could be broken out into a `RegistrationDomainService`? Similar to how `ContentPageService` has been created. @beforan @blargly should this be the case?

2021-05-14 12:05 UTC, Flemingjp commented on src/Entities/Data/RegistrationDomainRule.cs
> +
Another blank line

2021-05-14 12:12 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationDomainRuleController.cs
> +            var model = (await _biobankReadService.ListRegistrationDomainRulesAsync())
expression bodies <3

2021-05-14 12:18 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationDomainRuleController.cs
> +            });
blaaah so this way is consistent with the other "ApiControllers" in the Directory. They're not restful, they used to be "Ajax" methods in regular MVC Controllers...

if you look at `JsonModelInvalidResponse` you'll see it uses `success = false` and an HTTP 200.

Until we have the real API guaranteed to be deployed alongside the Directory, I think this is fine.

When that day comes, we'll require endpoints in the API to use HTTP Status codes.

2021-05-14 12:19 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationDomainRuleController.cs
> +            var model = (await _biobankReadService.ListRegistrationDomainRulesAsync()).First(x => x.Id == id);
yeah. and if it's null return success since this is a deletion.

2021-05-14 12:24 UTC, beforan submitted a review, later dismissed

2021-05-14 12:24 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/RegisterController.cs
> +            if (!await _biobankReadService.ValidateOrganisationEmail(model.Email) && !model.AdacInvited)
can we change this method name to `ValidateRegistrationEmailAddress`. Organisation is a bit loaded as it's an entity name, so could be confusing when it's used for Networks too. And we're validating the address, not an actual email message or anything :P

2021-05-14 12:24 UTC, beforan commented on src/Directory/Services/BiobankReadService.cs
> +                if ((await _registrationDomainRuleRepository.ListAsync(false, x => x.RuleType == "Block")).Where(y => email.Contains(y.Value)).Any())
`return <condition>`

2021-05-14 12:24 UTC, beforan commented on src/Directory/Services/BiobankWriteService.cs
> +        }
yes please. Separate Service for both reads and writes would be good, and don't use GenericRepository either, just use the DbContext directly, same as `ContentPageService`

2021-05-14 15:07 UTC, Flemingjp requested changes

2021-05-14 15:07 UTC, Flemingjp commented on src/Directory/Services/Contracts/IRegistrationDomainService.cs
> +        Task<RegistrationDomainRule> GetRegistrationDomainRuleByValueAsync(string ruleValue);
We are opting to drop `Async` from all service method names

2021-05-17 09:06 UTC, Flemingjp submitted a review, later dismissed

2021-05-17 09:08 UTC, blargly approved these changes

2021-05-17 09:11 UTC, Flemingjp commented on src/Directory/Services/RegistrationDomainService.cs
> +            {
Also to add - shouldnt it be `email.EndsWith(x.Value)`?

2021-05-17 13:07 UTC, blargly approved these changes

2021-05-17 13:53 UTC, JosephLavagna approved these changes

2021-05-17 14:09 UTC, merged