AB#32818: Mark API Collections as such and rules around GUI editing/viewing
biobankinguk/biobankinguk pull request #239
Opened 2021-05-19 16:42 UTC by shakisparki

## Overview

Description field remains editable, everything else is read only.

2021-05-20 07:27 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Controllers/BiobankController.cs
> +            if (model.FromApi)
Is it possible to do this check without relying on the model from the frontend? If you retrieve the collection beforehand, you can check if it's from the API using the backend data - this seems more reliable.

```c#
var collection = await _biobankReadService.GetCollectionByIdAsync(model.Id);

if (collection.FromApi)
{
}
```

2021-05-20 13:06 UTC, shakisparki commented on src/Directory/Biobanks.Web/Controllers/BiobankController.cs
> +            if (model.FromApi)
You are absolutely right

2021-05-20 13:58 UTC, beforan requested changes

2021-05-20 13:58 UTC, beforan commented on src/Directory/Biobanks.Web/Scripts/Biobank/collection-crud.js
> +    if (fromapi == "true") {
`===`, and perhaps also a comment to clarify that this is NOT a boolean value, it's a string because it comes from a form field.

I hate this code, but JS doesn't have anything better without us doing a LOT more work on preparing our viewmodels for JS usage... so for now we'll just warn people of its points of confusion.

2021-05-24 07:59 UTC, Flemingjp approved these changes

2021-06-02 12:33 UTC, beforan approved these changes

2021-06-02 12:57 UTC, merged