AB#34164: Manually Add Publications
biobankinguk/biobankinguk pull request #256
Opened 2021-06-03 13:14 UTC by shakisparki

## Overview

User could input pubmed id value, and add the returned publication to their Biobank. 

Call epmc API directly and look up the publication by the ID.

- User presses a button (in publications tab) which says "Add Publication"
- Brings up a modal with an input field for the pubmed Id
- Look at local db, see if its already associated (approved, rejected or just in the suggested list). If we have no result we then hit the API for the publication.
- Return publication information below the input and search.
- Then we also have an approve and cancel button and some text (If this is the correct publication, then press the approve button to add this publication to your Biobanks approved publications list.). Cancel just closes the modal.
- On Approve, return to index view with a Publication Added validation message, and update page.

2021-06-14 14:29 UTC, Flemingjp approved these changes

2021-06-14 14:29 UTC, Flemingjp reviewed
Will approve once conflict resolved

2021-06-14 14:57 UTC, Flemingjp requested changes

2021-06-14 14:57 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Controllers/BiobankController.cs
> +                        Path = "/europepmc/webservices/rest/search",
The Publications job uses `https://www.ebi.ac.uk/europepmc/` as the base URL - where here it assumes `https://www.ebi.ac.uk/` 

We should try keep it consistent between the two to avoid confusion in the configuration

2021-06-15 07:23 UTC, Flemingjp approved these changes

2021-06-16 12:04 UTC, blargly approved these changes

2021-06-16 14:36 UTC, merged