AB36366#: Analytics update
biobankinguk/biobankinguk pull request #257
Opened 2021-06-03 13:23 UTC by blargly

Added a new DTO for storing AnalyticsReportingKey, and converted from appsettings to this new object using IOptions.

2021-06-03 13:30 UTC, beforan commented on src/Submissions/Api/appsettings.json
> +  "Analytics": {
do we need the empty configs here? do they all default to null and cause problems or something? you can fix that by initializing the properties on the Options class?

2021-06-03 13:31 UTC, Flemingjp commented on src/Core/Analytics/Dto/GoogleAnalyticsReportingKey.cs
> +        public string type { get; set; }
Worth using the `[JsonProperty("")]` annotation to keep the field names C# compliant?

2021-06-03 13:45 UTC, beforan commented on src/Submissions/Api/appsettings.json
> +  "Analytics": {
Also `GoogleAnalyticsReportingKey` being an object could be really annoying to confiure in Azure Portal, KeyVault etc... a string would be simpler if we can get it working

2021-06-23 13:34 UTC, blargly commented on src/Core/Analytics/Dto/GoogleAnalyticsReportingKey.cs
> +        public string type { get; set; }
Sorted

2021-06-23 13:44 UTC, blargly commented on src/Submissions/Api/appsettings.json
> +  "Analytics": {
Gone with an object as its the only option I could get working.

re the appsettings - I've left it empty simply because it's easier for users to see what properties can be populated. Can appreciate that it's not essential though.

2021-06-24 08:20 UTC, Flemingjp requested changes

2021-06-24 08:20 UTC, Flemingjp commented on src/Directory/Services/AnalyticsService.cs
> +        private async Task<ProfileStatusDTO> GetProfileStatus(Organisation biobank)
Just two warnings to clear up here

2021-06-24 13:02 UTC, Flemingjp approved these changes

2021-06-24 13:19 UTC, beforan requested changes

2021-06-24 13:19 UTC, beforan commented on src/Directory/Services/AnalyticsService.cs
> +                var collection = _db.Collections.Include("SampleSets").SingleOrDefault(x => x.CollectionId == col.CollectionId);
this should still be async (use `SingleOrdefaultAsync()`), and therefore so should `GetProfileStatus()`

2021-06-24 13:19 UTC, beforan commented on src/Directory/Services/AnalyticsService.cs
> +        public AnalyticsService(BiobanksDbContext db)
really though, why bother renaming this service?

- it was already accurately named
- it gave a clearer indication of what it was used for than just "some kind of analytics stuff"
- it lines up with the equivalent analytics report generation services in Core

2021-06-24 13:19 UTC, beforan commented on src/Directory/Services/AnalyticsService.cs
> +            var biobank = _db.Organisations.SingleOrDefault(x => x.OrganisationId == Id);
this should still be async

2021-06-24 13:19 UTC, beforan commented on src/Submissions/Api/appsettings.json
> +  "Analytics": {
we need to decide to be consistent across all our code re: empty settings in appsettings.json, basically. and becuase of defaulting in Options classes, my vote is to leave them out (but document them)

2021-06-25 09:11 UTC, blargly commented on src/Directory/Services/AnalyticsService.cs
> +        public AnalyticsService(BiobanksDbContext db)
Is it accurate? It retrieves some data from the API for directory or biobank level reports. The "generating" of that report happened on the API side I would argue.

2021-07-01 12:22 UTC, closed without merging