AB#34697: Custom Page Creator
biobankinguk/biobankinguk pull request #258
Opened 2021-06-04 15:48 UTC by bradthompson995

## Overview

This implements the Custom Page Functionality which includes:

- Creating & Updating Custom Pages
- Custom Page ADAC Index
- Ability to access custom pages

Custom pages follow the following route schema:
/pages/**slug** (slug is the unique identifier used for each custom pages to access it.)

2021-06-04 16:32 UTC, Flemingjp commented on src/Directory/Biobanks.Web/packages.config
> -  <package id="MiniProfiler.Shared" version="4.2.1" targetFramework="net48" />
No need for the update here

2021-06-04 16:33 UTC, Flemingjp requested changes
All looks good - someone just need to pickup changes to prevent the version updates

2021-06-04 16:33 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Views/PagesAdmin/CreateEditPreview.cshtml
> +</style>
Move to `Style.css`

2021-06-04 16:33 UTC, Flemingjp commented on src/Directory/Biobanks.Web/packages.config
> +  <package id="MiniProfiler.Shared" version="4.2.22" targetFramework="net48" />
No need for the update here

2021-06-04 16:33 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Biobanks.Web.csproj
> +      <HintPath>..\packages\MiniProfiler.4.2.22\lib\net461\MiniProfiler.dll</HintPath>
No need for update here either

2021-06-15 10:28 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Views/PagesAdmin/CreateEditPreview.cshtml
> +</style>
This is actually inline with all other Preview Views

2021-06-15 12:56 UTC, beforan approved these changes

2021-06-17 08:35 UTC, blargly approved these changes

2021-06-17 08:40 UTC, merged