AB#32151: Add ExtractionProcedure API Controller and Service Methods
biobankinguk/biobankinguk pull request #268
Opened 2021-06-14 14:11 UTC by shakisparki

## Overview

Add an API Controller for Extraction Procedure - and create the required service methods alongside.

Note ExtractionProcedure is now a SnomedTerm and will need to be filtered from that table

Some bug fixes.

2021-06-14 14:26 UTC, Flemingjp approved these changes

2021-06-17 08:24 UTC, Flemingjp requested changes

2021-06-17 08:24 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/ExtractionProcedureController.cs
> +            var model = (await _biobankReadService.ListExtractionProceduresAsync()).Where(x => x.Id == id).First();
Better of creating a `GetExtractionProcedure` service method? That way you can do the filtering on database

2021-06-17 14:31 UTC, Flemingjp submitted a review, later dismissed

2021-06-21 14:21 UTC, beforan requested changes

2021-06-21 14:21 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/DiseaseStatusController.cs
> +                ModelState.AddModelError("Description", "That description is already in use by another disease status or extraction procedure. Disease status descriptions must be unique.");
I feel like this message is confusing everywhere it appears. In this particular case, the first clause mentions both ontology term types, but the second only mentions disease status, and if they're editing disease statuses mentioning extraction procedure out of the blue is just gonna confuse them.

I think something like "That description is already in use. Descriptions must be unique across all ontology terms." is less confusing but still accurate.

2021-06-21 14:21 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/DiseaseStatusController.cs
> +                ModelState.AddModelError("OntologyTermId", "This Id is currently in use by another Disease status or extraction procedure. Ontology Term Ids must be unique");
I would word this the same as the description message, but with "ID" instead.

2021-06-21 14:21 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/ExtractionProcedureController.cs
> +    //[UserApiAuthorize(Roles = "ADAC")]
why is this commented out? is that a mistake or should it be removed?

2021-06-21 14:21 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/ExtractionProcedureController.cs
> +                ModelState.AddModelError("Description", "That description is already in use by another disease status or extraction procedure. Extraction procedure descriptions must be unique.");
Simplify this / make it consistent with elsewhere

2021-06-28 08:31 UTC, closed without merging

2021-06-28 08:31 UTC, blargly commented
No longer needed