AB#35720: Diagnosis Display on Directory UI
biobankinguk/biobankinguk pull request #278
Opened 2021-06-25 13:25 UTC by Flemingjp

- Disease Status ADAC UI
  - Added DisplayOnDirectory Column
  - Added DisplayOnDirectory Checkbox on Add/Edit Modal
  - Displays all OntologyTerms rather than those just flagged DisplayOnDirectory
  - Moved from static generated DataTable to dynamic ajax DataTable
    - New PaginatedDiseaseStatus endpoint
    - Action links are generated on the frontend instead
    - Removal of legacy data bindings where applicable
  - Removal of model on DiseaseStatus View

2021-06-28 13:56 UTC, beforan requested changes

2021-06-28 13:56 UTC, beforan commented on src/Directory/Services/Contracts/IBiobankReadService.cs
> +        Task<IEnumerable<OntologyTerm>> ListOntologyTerms(string filter = "", bool onlyDisplayable = false);
1. why isn't this async?
2. it has also essentially been replaced (or the old async version has) by the newer `ListDiseaseOntologyTermsAsync()`? (or something like that) so needs to take that filtering into account, since I think it's supposed to be getting disease statuses only

2021-06-28 13:56 UTC, beforan commented on src/Directory/Services/Contracts/IBiobankReadService.cs
> +        Task<IEnumerable<OntologyTerm>> ListDisplayableOntologyTerms(string filter = "");
Similar to above, I think this should also be getting Disease Statuses only, and so additional filtering may be needed.

2021-07-01 09:05 UTC, beforan approved these changes

2021-07-01 09:07 UTC, blargly approved these changes

2021-07-01 09:07 UTC, merged