AB#36916: Config Service
biobankinguk/biobankinguk pull request #285
Opened 2021-07-06 13:57 UTC by JosephLavagna

- Take existing config services from the read/write services
- Specific methods dealing with boolean flags only. Handles the conversion from strings to bools within the method to avoid any type issues doing it manually. Instances where a boolean value is being used should make use of this method.

- Will be creating FlagController with SuperUser flag view in PBI #36740 which will make use of the ConfigService and methods created for this PR.

2021-07-06 14:10 UTC, beforan requested changes

2021-07-06 14:10 UTC, beforan commented on src/Directory/Services/ConfigService.cs
> +        public async Task<bool> GetSiteConfigStatus(string siteConfigValue)
I don't think this method (or its argument) is clearly named. But also, what is its purpose?

It seems to do the same job as `GetFlagConfigValue()`, but less well.

2021-07-06 14:10 UTC, beforan commented on src/Directory/Services/ConfigService.cs
> +        public async Task<List<Config>> ListBooleanFlags(bool includeFeatures, string wildcard = "")
`includeFeatures` is mis-named. the functionality is actually "not features" when it's `false`, and "only features" when it's `true`. To get ALL boolean config records, you'd have to call it twice.

Not sure what the fix is. If this provides the required functionality adequately, then probably just rename the argument? Not sure what to though. `isFeatureFlag` probably, since then it's setting the expected value of the column (though for false, null is also valid... maybe a doc comment could clear that up)

2021-07-06 14:54 UTC, JosephLavagna commented on src/Directory/Services/ConfigService.cs
> +        public async Task<bool> GetSiteConfigStatus(string siteConfigValue)
This method was moved over from ReadService but yep it does seem to do the same thing as `GetFlagConfigValue()` - will remove the method and update references

2021-07-06 14:54 UTC, JosephLavagna commented on src/Directory/Services/ConfigService.cs
> +        public async Task<List<Config>> ListBooleanFlags(bool includeFeatures, string wildcard = "")
Yep wasn't too sure on this - I could make it a nullable bool - which would allow for the three different possible scenarios: 
(1) - Get all boolean flags (no matter if feature or not) - (param = null)
(2) - Get boolean flags only where `isFeatureFlag` == true - (param = true)
(3) - Get boolean flags only where `isFeatureFlag` == false || null - (param = false)

Not ideal, and would not work with the idea of the expected value of the `isFeatureFlag` column. 
Or could separate into two methods - one which just grabs  all boolean flags and another which grabs all flags(bool isFeature).

2021-07-07 08:25 UTC, beforan commented on src/Directory/Services/ConfigService.cs
> +        public async Task<List<Config>> ListBooleanFlags(bool includeFeatures, string wildcard = "")
yeah i thought about nullable bool but i thought that would be misleading in it's own way, especially since the column is also nullable (but for the column null means false!).

Arguably the actually right thing to do would be an enum that allows you to specify which of the 3 behaviours you want.
Actually, I think that's probably right. It can be in this file since it's an option exclusively for this service. 

so something like 

```csharp
enum BooleanConfigSelection {
  FeatureFlagsOnly
  ExcludeFeatureFlags
  AllBooleanConfigs
}
```

then default the the argument to AllBooleanConfigs, and then if people want only flags, or only NOT flags, they can specify.

Not wedded to those names, if you can find a clearer way of expressing them, go for it :)

2021-07-07 14:32 UTC, beforan approved these changes

2021-07-07 15:16 UTC, shakisparki commented on src/Directory/Biobanks.Web/Controllers/ADACController.cs
> +using static Biobanks.Services.ConfigService;
Is this necessary?

2021-07-07 15:19 UTC, JosephLavagna commented on src/Directory/Biobanks.Web/Controllers/ADACController.cs
> +using static Biobanks.Services.ConfigService;
Yep it is - when calling the  `ListBooleanFlags()` method you need to pass it a 'selection' of the enum - `BooleanConfigSelection` and this needs that reference to do so.

2021-07-07 15:21 UTC, shakisparki approved these changes

2021-07-07 15:21 UTC, merged

2021-07-07 16:59 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/ADACController.cs
> +using static Biobanks.Services.ConfigService;
i assume it's because it's referencing the enum member of the class, in which case, yes.