AB#38414: Include Findings in Search Typeahead
biobankinguk/biobankinguk pull request #293
Opened 2021-07-20 09:46 UTC by Flemingjp

Currently the search typeahead will only show results for Ontology Disease Terms that are found in the search index. This means the often used `Fit and well (finding)` term is excluded, as it is a Finding. 

This PR introduces findings to be included in the search typeahead

2021-07-21 13:49 UTC, shakisparki approved these changes

2021-07-22 08:24 UTC, beforan requested changes

2021-07-22 08:24 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/SearchController.cs
> +                .Concat(directoryFindingTerms)
ok but we could just do this in one sql call...

hate to say it, but having merged the previous changes around filtering and providing domain specific ontologyterm getters, maybe we need to refactor into one method that includes whatever tags you ask for in one go?

Will make this more efficient, simpler and easier to grok, and also remains extensible for the future.

so something like:

```csharp
List<OntologyTerm> ListOntologyTerms(List<string> includeTags = null, onlyDisplayable = (whatever the default is))
{
  var query = _db.OntologyTerms
    .Where(x => x.DisplayOnDirectory || !onlyDisplayable);
    // include the wildcard Where() clause here if filtering by wildcard
  
  if(includeTags != null)
  {  
    if(!includeTags.Any()) // get only untagged terms
      query = query.Where(x => x.SnomedTag == string.Empty || null);

    includeTags.ForEach(tag => { query = query.Where(x => x.SnomedTag == tag); }
  }
  // else - get everything regardless of tag

  return query.ToListAsync();
}
```

If the above doesn't work exactly as I think (chaining `Where`) then can use LinqKit's `PredicateBuilder` instead.

Also doc comment the `includeTags` parameter to be clear about the difference between `null` and an empty list, if you do it this way :) Open to a different and better API if you've got one though.

probably also change the tag strings from the constants they are now to an actual static constants class (this is a pattern we already use).

```csharp
public static class SnomedTags {
  public const string Disease = "Disease";
  // ...
}
```

Doing this refactor saves on the almost exact duplicating below, and provides an oportunity to escape the `GenericRepository` for these cases. ;)

2021-07-23 07:40 UTC, beforan commented on src/Directory/Services/Constants/SnomedTags.cs
> +    }
should there be a tag for extraction procedure?

2021-07-23 08:19 UTC, blargly approved these changes

2021-07-23 08:26 UTC, beforan commented on src/Directory/Services/Constants/SnomedTags.cs
> +    }
yes, but work for this is currently captured in AB#37807

2021-07-23 08:27 UTC, beforan approved these changes

2021-07-23 08:27 UTC, merged