AB#38419: Create collection view - fit and well not showing on disease status typeahead
biobankinguk/biobankinguk pull request #295
Opened 2021-07-20 14:02 UTC by shakisparki

## Overview

Go to create collection view - begin to type "Fit and Well (Finding)". This does not display in the typeahead.
Furthermore, if the entire term is entered into the field, and rest of the form is valid, an error is returned relating to the disease status field.

2021-07-20 15:39 UTC, Flemingjp requested changes

2021-07-20 15:39 UTC, Flemingjp commented on src/Directory/Services/Contracts/IBiobankReadService.cs
> +        Task<IEnumerable<OntologyTerm>> ListDiseaseFindingOntologyTermsAsync(string wildcard = "", bool onlyDisplayable = false);
I understand where this naming comes from, but I think it would be more concise to cut it down to something like `ListFindingOntologyTerms` - including dropping `Async`

2021-07-20 15:39 UTC, Flemingjp commented on src/Directory/Services/BiobankReadService.cs
> +        public async Task<IEnumerable<OntologyTerm>> ListDiseaseFindingOntologyTermsAsync(string wildcard = "", bool onlyDisplayable = false)
I think it'd be much clearer to have this just return Findings, from a service method point of view. Then if both Disease and Findings are required, they are called together and the results concatenated where needed.

If this dual method is truly needed, it should be a third service method that calls the previous two.

2021-07-20 15:39 UTC, Flemingjp commented on src/Directory/Services/BiobankReadService.cs
> +        public async Task<bool> ValidDiseaseFindingOntologyTermDescriptionAsync(string ontologyTermDescription)
Same idea here. We can validate twice

2021-07-21 10:04 UTC, blargly commented on src/Directory/Services/Contracts/IBiobankReadService.cs
> +        Task<IEnumerable<OntologyTerm>> ListDiseaseFindingOntologyTermsAsync(string wildcard = "", bool onlyDisplayable = false);
This is my bad as I added this in my branch, but good point.

2021-07-21 10:05 UTC, blargly commented on src/Directory/Services/BiobankReadService.cs
> +        public async Task<IEnumerable<OntologyTerm>> ListDiseaseFindingOntologyTermsAsync(string wildcard = "", bool onlyDisplayable = false)
This is my bad, as I did this in my branch, but yes good point to seperate.

2021-07-21 10:27 UTC, Flemingjp approved these changes

2021-07-21 11:15 UTC, blargly approved these changes

2021-07-21 11:15 UTC, merged