AB#38420: Extraction Procedure config page does not display displayinDirectory=0 entries
biobankinguk/biobankinguk pull request #296
Opened 2021-07-22 13:19 UTC by shakisparki

## Overview

Adds option to turn on and off DisplayOnDirectory for extraction procedures

2021-07-23 09:03 UTC, beforan requested changes

2021-07-23 09:03 UTC, beforan commented on src/Directory/Services/BiobankReadService.cs
> +        public async Task<IEnumerable<OntologyTerm>> ListExtractionProceduresAsync(string wildcard = "", bool onlyDisplayable = false)
most of these service methods can move to the new generalised OntologyTerms methods (where you specify which tags to include).

2021-07-23 09:04 UTC, beforan commented on src/Directory/Services/BiobankReadService.cs
> +        public async Task<IEnumerable<OntologyTerm>> ListExtractionProceduresAsync(string wildcard = "", bool onlyDisplayable = false)
need to add Extraction Procedure tag value to the new SnomedTags constants class too

2021-07-26 14:19 UTC, Flemingjp requested changes

2021-07-26 14:19 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/ExtractionProcedureController.cs
> +            }, false);
Specify the parameters by name to avoid random null values, and to add clarity

```c#
var model = await _biobankReadService.GetOntologyTerm(id, onlyDisplayable: false, tags: new List<string> 
{ 
    SnomedTags.ExtractionProcedure 
});
```

2021-07-26 14:19 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Controllers/BiobankController.cs
> +                },true))
Same here. `onlyDisplayable` is also true by default

2021-07-26 14:19 UTC, Flemingjp commented on src/Directory/Services/BiobankReadService.cs
> +        public async Task<IEnumerable<OntologyTerm>> GetMaterialTypeExtractionProcedures(int id, bool onlyDisplayable = false)
Can we standardise the `onlyDisplayable` flag default across service methods. Either all should be `true` or `false` - my preference would be to `false` such that an additional filter isnt imposed by default

2021-07-26 16:22 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/ExtractionProcedureController.cs
> +            if ((await _biobankReadService.ListOntologyTerms()).Any(x=>x.Value == model.Description && x.Id != id))
Why change to this method?

2021-07-27 07:54 UTC, beforan approved these changes

2021-07-27 13:17 UTC, shakisparki commented on src/Directory/Biobanks.Web/ApiControllers/ExtractionProcedureController.cs
> +            if ((await _biobankReadService.ListOntologyTerms()).Any(x=>x.Value == model.Description && x.Id != id))
The use of ValidOntologyTerm in this way prevents updating an ontologyterm without changing the description.
This restricts a PUT operation for example when you want to update something else like just the material type.

Ofcourse this is potentially an issue with all other Api controllers that use the Valid...methods. However it doesn't pose a problem for most as they have one editable field which is the description. In these cases, updating the description without changing it fails but this isn't a functional problem.

2021-07-27 15:09 UTC, Flemingjp approved these changes

2021-07-27 15:22 UTC, merged