AB#38662: Refactor Into OntologyTerm Service
biobankinguk/biobankinguk pull request #299
Opened 2021-07-28 11:18 UTC by Flemingjp

Moved all OntologyTerm service methods into a dedicated `OntologyTermService`

2021-07-29 14:23 UTC, beforan requested changes

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +    public interface IOntologyTermService
Doc comments everywhere in here please.

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<IEnumerable<OntologyTerm>> ListOntologyTerms(string description = null, List<string> tags = null, bool onlyDisplayable = false);
Call it `List()`

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<IEnumerable<OntologyTerm>> PaginateOntologyTerms(int start, int length, string description = null, List<string> tags = null);
don't need `OntologyTerm` in any of the method names; that should be the default assumption on an `OntologyTermService`

for this one, not sure if I prefer `Paginate()` or `ListPaginated()` (which I think is technically more correct)

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<OntologyTerm> GetOntologyTerm(string id = null, string description = null, List<string> tags = null, bool onlyDisplayable = false);
`Get()`

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<bool> ValidOntologyTerm(string id = null, string description = null, List<string> tags = null);
`IsValid()`

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<bool> IsOntologyTermInUse(string id);
`IsInUse()`

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<int> CountOntologyTerms(string description = null, List<string> tags = null);
`Count()`

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<int> GetCollectionCapabilityCount(string id);
This is a hard one, though partly cos without docs I don't 100% know what it does. I assume count Collecitons and Capabilities whose diagnosis is this term?

So something like `CountCollectionCapabilityByDiseaseStatus(string diseaseStatusId)` should make it a bit clearer? Not 100% sold on that though.

Def change the parameter name though, since the id doesn't directly relate to the types metnioned in the method name, so be explicit.

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task DeleteOntologyTerm(string id);
`Delete()`

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<OntologyTerm> UpdateOntologyTerm(OntologyTerm ontologyTerm);
`Update()`

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<OntologyTerm> AddOntologyTerm(OntologyTerm ontologyTerm);
Not sure if I prefer `Create()` rather than `Add()` here? Kind of a consistency call as it sets the convention for future primarily entity typed services?

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/OntologyTermService.cs
> +                .AsNoTracking()
Be careful with this. I might change the method name to `ReadOnlyQuery()` or something, to be clear that this particular IQueryable has tracking off.

Or parameterise tracking and default to off...

Just don't want people accidentally using it for write activity and wondering why it's not tracking.

(This is one advantage of the old separate Read and Write services; the Read Service *never* needs tracking)

2021-07-29 14:23 UTC, beforan commented on src/Directory/Services/OntologyTermService.cs
> +            // TODO: Check If Manual Update Of Material Types Is Required
has this been resolved?

2021-07-29 14:26 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<OntologyTerm> AddOntologyTerm(OntologyTerm ontologyTerm);
but the term in `CRUD` is `Create` so that's where I'm coming from

2021-07-29 14:29 UTC, beforan commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<IEnumerable<OntologyTerm>> PaginateOntologyTerms(int start, int length, string description = null, List<string> tags = null);
Also, I don't like `start` and `length`.

`offset` and `limit` are terms i've used in the past, and i think are common (though that may be anecdotally)

alternatively, since we're in c#, why not `skip` and `take` to match the underlying Linq.

2021-07-29 14:35 UTC, Flemingjp commented on src/Directory/Services/Contracts/IOntologyTermService.cs
> +        Task<OntologyTerm> AddOntologyTerm(OntologyTerm ontologyTerm);
Gone with `Create` - don't know why but it sounds more permanent

2021-07-30 08:32 UTC, beforan submitted a review, later dismissed

2021-08-02 12:24 UTC, Flemingjp commented on src/Directory/Services/OntologyTermService.cs
> +            // TODO: Check If Manual Update Of Material Types Is Required
I have managed to resolve the issue for the Update method. However the Add method is still creating duplicate MaterialTypes rather than referencing existing MaterialTypes

2021-09-09 09:33 UTC, Flemingjp commented
As mentioned in #315 - there needs to be a distinct and clear difference in the service for where we want to retrieve OntologyTerms using the exact description or using it as a wildcard.

- Exact in almost all cases
- Wildcard for search cases (eg Search Type-Ahead)

2021-09-24 10:24 UTC, beforan approved these changes

2021-09-24 12:46 UTC, blargly approved these changes

2021-09-24 12:47 UTC, merged