AB#38959: Reference Data Service
biobankinguk/biobankinguk pull request #314
Opened 2021-09-06 09:28 UTC by Flemingjp

2021-09-07 13:55 UTC, Flemingjp commented on src/Directory/Services/Contracts/IReferenceDataService.cs
> +    }
There is scope for two additional methods `Task<int> GetUsageCount(int id)` and `Task<bool> IsInUse(int id)` 

The issue here is that these methods, while are applicable to all/most ReferenceData types, do not have a common generic implementation, as the usage typically depends on another entity. For example, for `AccessCondition` usage depends on the number of Collections it is used in.

I think the options are

- These methods are included with a default implementation
  - Cons: Requires sensible defaults that may not exist `(Usage = 0, InUse=false)` are those sensible? 
- These methods are included as abstract methods, making the base service abstract
  - Cons: Then requires an implementing class per each reference data type
- These methods are not included
  - Cons: Requires a specific implementation per each reference data type that requires these methods

2021-09-08 09:18 UTC, Flemingjp commented on src/Directory/Services/ReferenceDataService.cs
> +        public async Task<bool> ExistsByValue(string value)
`ExistsByValue` or just `Exists` as an method overload?

2021-09-08 09:32 UTC, beforan commented on src/Directory/Services/ReferenceDataService.cs
> +        public async Task<bool> ExistsByValue(string value)
vastly prefer overload myself

2021-09-08 09:37 UTC, beforan commented on src/Directory/Services/Contracts/IReferenceDataService.cs
> +    }
default implementation no. it's too dangerous.

abstract vs exclude depends on 2 things, I think:
- How many concrete implementations do we save ourselves by not going the abstract route. My guess is not many, but that will be a factor as to whether or not it's "worth" not doing.
- How meaningful is it for stuff higher up to know that it can ask a service for usage information? Does it have to opt into that by a specific service type for a specific refdata type, just like bounds and other extended functionality? Or should it be reasonably assumed that you can ask that information about all refdata. Actually, this is probably largely informed by the point above ¯\_(ツ)_/¯

My gut feel, though subject to the above, is that abstract is the Right Thing To Do™, despite resulting in needing concrete implementations for all refdata.

At the end of the day, we are still using inheritance, so those multiple implementations are still more concise and DRY than they would otherwise have been.

2021-09-15 10:01 UTC, beforan requested changes

2021-09-20 08:41 UTC, beforan approved these changes

2021-09-20 09:04 UTC, blargly approved these changes

2021-09-20 09:05 UTC, merged