AB#47362: Copy Collection
biobankinguk/biobankinguk pull request #361
Opened 2022-01-21 16:05 UTC by aydtmiri

Added logic to copy collections, including SampleSets, Materials etc.

2022-01-21 16:19 UTC, beforan requested changes

2022-01-21 16:19 UTC, beforan commented on sql/add-user.sql
> +SET @Email = 'miriam.aydt@nottingham.ac.uk'
probably don't want to commit these changes :)

2022-01-25 10:25 UTC, blargly commented on src/Directory/Biobanks.Web/Controllers/BiobankController.cs
> +            var collectionToCopy = await _collectionService.Get(id);
So lines 1035 to 1096 could move, just pass the collection id as a param then

2022-01-26 09:09 UTC, blargly approved these changes

2022-01-26 13:56 UTC, beforan approved these changes

2022-01-26 14:03 UTC, merged