Publications migration to Azure Key Vault
biobankinguk/biobankinguk pull request #37
Opened 2020-08-28 09:49 UTC by Flemingjp

Migrated storing database credentials to the Azure Key Vault. The azure pipelines is now configured to fetch these credentials during the Deploy stage, and are subsequently used to deploy the database migration. The pipeline is also used to apply KeyVault references to the Azure Functions App. This allows the Azure Functions App to access the credentials from the functions app settings at runtime - without needing to access the KeyVault via the codebase.

Also migrated the api urls to the app settings from the connection strings - as recommended by Microsoft in their documentation.

Also changed the EpmcFunction to use the correct service `EpmcService => PublicationService`

2020-09-08 14:39 UTC, blargly commented on .azure/pipelines/publications.yml
> +  resourceGroupName: 'biobankinguk-services-test'
The resource group should be 'biobankinguk-directory-test' as that's the existing one we're using for the test environment.

2020-09-08 14:39 UTC, blargly commented on .azure/pipelines/publications.yml
> +  keyVaultName: 'biobanking-services-test'
The existing keyvault in the above resource Group is 'directoryTestKeyvault'

2020-09-08 14:39 UTC, blargly commented on .azure/pipelines/publications.yml
> +  dbServerName: 'biobankinguk-services-test.database.windows.net'
Again, may as well use an existing resource: 'biobankinguk-directory-test'

2020-09-09 08:07 UTC, beforan approved these changes

2020-09-09 08:53 UTC, beforan requested changes

2020-09-09 08:53 UTC, beforan commented on src/Publications/PublicationsAzureFunctions/Startup.cs
> +            _configuration = builder.Services.BuildServiceProvider()
for this, can we build only the configuration early, rather than the entire service tree?

```suggestion
            _configuration = builder.ConfigurationBuilder.Build();
```

2020-09-09 09:20 UTC, beforan requested changes

2020-09-09 09:20 UTC, beforan commented on src/Publications/Publications/Services/EpmcWebService.cs
>          public EpmcWebService(IHttpClientFactory httpClientFactory, IConfiguration configuration)
All the services you use `HttpClientFactory` in don't need to dispose the client anymore.

2020-09-09 10:03 UTC, Flemingjp commented on src/Publications/PublicationsAzureFunctions/Startup.cs
> +            _configuration = builder.Services.BuildServiceProvider()
`IFunctionsHostBuilder` only exposes the Services property - maybe another way to do this?

2020-09-09 12:58 UTC, blargly approved these changes

2020-09-09 13:10 UTC, beforan commented on src/Publications/PublicationsAzureFunctions/Startup.cs
> +            _configuration = builder.Services.BuildServiceProvider()
yeah, my bad. misread the docs

2020-09-09 13:57 UTC, beforan approved these changes

2020-09-09 13:59 UTC, merged