AB#46818: Omop context
biobankinguk/biobankinguk pull request #376
Opened 2022-03-04 10:47 UTC by aydtmiri

Added Omop Context

2022-03-04 13:17 UTC, beforan requested changes

2022-03-04 13:17 UTC, beforan commented on src/Omop/Omop/Context/OmopDbContext.cs
> +        //public class OmopDbContextFactory : IDesignTimeDbContextFactory<OmopDbContext>
All this commented code can go. We don't need it since we aren't running migrations against this context

2022-03-04 13:17 UTC, beforan commented on src/Omop/Omop/Entities/ConditionOccurence.cs
> +        public int ConditionOccurenceId { get; set; }
is this actually a primary key? If so, can we use the `[Key]` attribute on it, and then you don't need the unique constraint configured on the context either?

If not, then fair enough :P

2022-09-28 11:15 UTC, blargly approved these changes

2022-09-28 11:19 UTC, AndyRae approved these changes

2022-09-28 11:26 UTC, merged