Analytics azure functions
biobankinguk/biobankinguk pull request #38
Opened 2020-09-02 16:54 UTC by shakisparki

Analytics Azure functions and class libraries.
Pipelines to deploy to test environment will be added in separate pull request

2020-09-09 09:57 UTC, beforan requested changes

2020-09-09 09:57 UTC, beforan commented on src/Analytics/Services/BiobankWebService.cs
> +            _client.BaseAddress = new Uri(configuration.GetConnectionString("Directory"));
this shouldn't be a connection string really, just a straight config value for `DirectoryUrl`. connection string implies database.

2020-09-09 09:57 UTC, beforan commented on src/Analytics/Services/BiobankWebService.cs
> +            _client.Dispose();
this is unnecessary now you're using `HttpClientFactory`

2020-09-09 09:57 UTC, beforan commented on src/Analytics/Services/Contracts/IGoogleAnalyticsReadService.cs
> +        Task StartAsync(CancellationToken cancellationToken);
are these (`StartAsync` and `StopAsync`) not part of `IHostedService`?

2020-09-09 09:57 UTC, beforan commented on src/Analytics/Services/Dto/OrganisationAnalyticReportDTO.cs
> +    public class QuarterlySummary
Should this be here? Is it a DTO? Should it have `DTO` in its name for consistency, or should it be elsewhere?

At minimum, it's not referentially related to the other classes in this file and so should probably be in its own file

2020-09-09 09:57 UTC, beforan commented on src/Analytics/Services/Dto/OrganisationAnalyticReportDTO.cs
> +    public partial class ProfileStatusDTO
this doesn't appear to relate directly to the primary class in this file `OrganisationAnalyticReportDTO`.

Can it move to its own file?

2020-09-09 09:57 UTC, beforan commented on src/Analytics/Services/Dto/OrganisationAnalyticReportDTO.cs
> +using System.Collections.Generic;
Can we properly case all the DTO class names (and preferably filenames, though I know changing case is a pin on NTFS).

it should be `Dto` even though it's an acronym, in PascalCase. https://stackoverflow.com/a/15526526/3191945

2020-09-09 13:11 UTC, beforan commented on src/Analytics/AzureFunctions/Startup.cs
> +            var config = builder.Services.BuildServiceProvider()
turns out we can't do the configuration builder like that, sadly.

So just get rid of the local variable here, ty.

2020-10-02 09:39 UTC, beforan requested changes

2020-10-02 09:39 UTC, beforan commented on src/Analytics/Analytics/AnalyticsDbContext.cs
> +                options.UseSqlServer(Environment.GetEnvironmentVariable("analyticsdb_connection"), options => options.EnableRetryOnFailure());
can't see in the pipeline yaml where the `analyticsdb_connection` env variable is being set, so not sure how migrations are running during deployment?

2020-10-02 09:39 UTC, beforan commented on src/Analytics/Services/AnalyticsReportGenerator.cs
> +        private readonly string hostname;
convention would suggest all these should have leading underscores.

Honestly not sure why VS doesn't spam you with suggestions to that effect.

2020-10-02 09:39 UTC, beforan commented on src/Analytics/Services/AnalyticsReportGenerator.cs
> +            this.numOfTopBiobanks = Convert.ToInt32(Environment.GetEnvironmentVariable("metric-threshold"));
shouldn't need to use `this`? and following the leading underscore convention for private fields makes it as clear as `this` anyway.

2020-10-02 09:39 UTC, beforan commented on src/Analytics/Services/Contracts/IGoogleAnalyticsReadService.cs
> +        //REMOVE TEST FUNC
should the function be removed at this time? or just the comment?

If it is a comment for a future action, please provide a `TASK:` prefix like `TODO:` so that tooling can find it

2020-10-02 09:39 UTC, beforan commented on src/Analytics/readme.md
> +-Code adapted from 'biobanks.analytics' repo in python. See for more information
could probably stand to link to the repo, or clarify that it's in Azure DevOps and relevant UoN people should have access.

2020-10-05 09:33 UTC, shakisparki commented on src/Analytics/Analytics/AnalyticsDbContext.cs
> +                options.UseSqlServer(Environment.GetEnvironmentVariable("analyticsdb_connection"), options => options.EnableRetryOnFailure());
it's done on line 81 of the YAML

2020-10-05 13:45 UTC, beforan requested changes

2020-10-05 13:45 UTC, beforan commented on src/Analytics/Services/AnalyticsReportGenerator.cs
> +            _numOfTopBiobanks = Convert.ToInt32(Environment.GetEnvironmentVariable("metric-threshold"));
Why are these getting environment variables? Can't they use `IConfiguration`?

2020-10-06 13:40 UTC, beforan approved these changes

2020-10-09 13:19 UTC, blargly approved these changes

2020-10-09 13:19 UTC, merged