AB#47303: Added related associated data in 'add collection'
biobankinguk/biobankinguk pull request #386
Opened 2022-05-23 13:19 UTC by Samad198

## Overview

Changed behaviour of associated data list inside 'add collection' page to add and remove data depending on Disease status input

## Azure Boards

- AB#47303
- AB#47306
- AB#47304

2022-05-23 14:29 UTC, beforan requested changes

2022-05-23 14:29 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/BiobankController.cs
> +            string ontologyTermId = null)
You don't seem to have updated anywhere this is _called_ so `ontologyTermId` will always be `null` and your new code will never run?

Also, I'm not sure a new argument passing ontologyTermId is the right way to do this? It's certainly not clear what the effect is going rto be, and the `AbstractCRUDCapabilityModel` already has the property `Diagnosis` containing a Diagnosis restricted OntologyTerm value, so you can get the ID the same way other methods do from a model taht only contains a value: `var ontologyTerm = await _ontologyTermService.Get(value: model.Diagnosis);` (e.g. [in AddCollection](https://github.com/biobankinguk/biobankinguk/blob/a8c166dee135021a8fee37eb7719acf9ef516f83/src/Directory/Biobanks.Web/Controllers/BiobankController.cs#L989)

2022-05-23 14:29 UTC, beforan commented on src/Directory/Biobanks.Web/Scripts/Shared/diagnosis-type-ahead.js
> +                                            Immediate
These timeframes can't be hardcoded. They're based on database records, so you need to render on the page what comes out of the db for timeframes.

The server side views do this, so the dynamic client side bits need to too, I'm afraid.

On the server side MVC - the ViewModel and [EditorTemplate](https://github.com/biobankinguk/biobankinguk/blob/main/src/Directory/Biobanks.Web/Views/Biobank/EditorTemplates/AssociatedDataModel.cshtml) particularly - does lots of the heavy lifting in terms of generating the markup.

Perhaps this JS should ask the server for markup, and then add that to the page? We do this elsewhere, e.g. [here we render a Partial View in an "ajax endpoint" and it gets inserted into a modal i believe](https://github.com/biobankinguk/biobankinguk/blob/a8c166dee135021a8fee37eb7719acf9ef516f83/src/Directory/Biobanks.Web/Controllers/BiobankController.cs#L665)

2022-05-23 14:29 UTC, beforan commented on src/Directory/Biobanks.Web/Views/Biobank/_CollectionSharedFields.cshtml
> +        @Html.TextBoxFor(x => x.Diagnosis, new { @class = "form-control diagnosis-search",@id="diagnosis-textbox", autocomplete = "off" })
any reason to add this `id`? can't you just select on the `diagnosis-search` class? that seems to be what other code was already doing

2022-05-23 16:13 UTC, Samad198 commented on src/Directory/Biobanks.Web/Views/Biobank/_CollectionSharedFields.cshtml
> +        @Html.TextBoxFor(x => x.Diagnosis, new { @class = "form-control diagnosis-search",@id="diagnosis-textbox", autocomplete = "off" })
Just removed it. Was no need for it

2022-05-24 16:14 UTC, Samad198 commented on src/Directory/Biobanks.Web/Scripts/Shared/diagnosis-type-ahead.js
> +                                            Immediate
Have now added this

2022-05-24 16:30 UTC, Samad198 commented on src/Directory/Biobanks.Web/Controllers/BiobankController.cs
> +            string ontologyTermId = null)
Seems i was confused on what I needed to do. Have removed it now

2022-05-25 09:13 UTC, blargly approved these changes

2022-05-25 09:49 UTC, beforan requested changes

2022-05-25 09:49 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/BiobankController.cs
> +        public async Task<ActionResult> GetAssociatedDataTypeViews(string id)
Can you put `Ajax` on the end of this.

I know it's kinda dumb but it matches the convention used elsewhere in this app when there are Controller actions on non API Controllers intended for use in AJAX calls.

2022-05-25 12:47 UTC, Samad198 commented on src/Directory/Biobanks.Web/Controllers/BiobankController.cs
> +        public async Task<ActionResult> GetAssociatedDataTypeViews(string id)
Done

2022-05-26 08:40 UTC, beforan approved these changes

2022-05-26 11:13 UTC, blargly approved these changes

2022-05-26 11:14 UTC, merged