AB#47295: New Ontology term table column
biobankinguk/biobankinguk pull request #395
Opened 2022-06-07 13:29 UTC by Samad198

## Overview

Added associated data column to disease status table

## Azure Boards

- AB#47295

## Screenshots
<img width="912" alt="image" src="https://user-images.githubusercontent.com/38753056/172391226-d989f3b3-abdd-4a4a-b52a-dcad36b0093c.png">

2022-06-07 13:38 UTC, beforan requested changes

2022-06-07 14:36 UTC, dcl10 submitted a review, later dismissed

2022-06-08 08:38 UTC, MoizIqbal97 requested changes

2022-06-08 08:38 UTC, MoizIqbal97 commented on src/Directory/Biobanks.Web/Scripts/ADAC/adac-disease-statuses.js
> +          console.log(data);
Please remove unused Console.log

2022-06-08 08:42 UTC, MoizIqbal97 submitted a review, later dismissed

2022-09-23 13:26 UTC, dcl10 submitted a review, later dismissed

2022-09-23 13:50 UTC, AndyRae approved these changes

2022-09-26 08:50 UTC, blargly approved these changes

2022-09-26 08:54 UTC, AndyRae approved these changes

2022-09-26 09:00 UTC, merged