Writing publication data to the Directory DB
biobankinguk/biobankinguk pull request #40
Opened 2020-10-19 14:56 UTC by shakisparki

Writing publication data to the Directory DB instead of separate publications db

2020-10-20 07:55 UTC, beforan commented on src/Publications/Publications/Repositories/GenericEFRepository.cs
> +using Microsoft.EntityFrameworkCore;
Please god no do not use this code. This class needs to die.

This is a new app with EF Core, just use the DbContext directly, since that is in effect an implementation of the repository pattern.

2020-10-20 07:55 UTC, beforan commented on src/Publications/Publications/Repositories/IGenericEFRepository.cs
> +    public interface IGenericEFRepository<TEntity>
Obviously this can go too

2020-10-20 07:55 UTC, beforan commented on src/Publications/Publications/PublicationDbContext.cs
> +        public DbSet<Organisation> Organisations { get; set; }
If this is read-only it can (should?) be a `DbQuery<T>` not a `DbSet`

2020-10-20 07:55 UTC, beforan commented on src/Publications/Publications/Entities/Organisation.cs
> +    public class Organisation
I'm quite uncomfortable with duplicating this entity over here in this codebase.

The right thing to do would be to put entities in a class library and reference that everywhere that uses those entities. This is close to the fact the Data stuff in the Directory is already in a class library, but I recognise the need to have the entities separate from the Contexts/Migrations, especially in view of the fact that's EF6 and everything newer is likely to be EF Core.

If, as in an ideal world, this code and the directory code were in the same repo, a class library of entities would be a no brainer.

Sadly, due to the different repos currently (and probably for a while longer), we'd have to publish a nuget package of the entities to share them, or use git submodules. Definitely faffy.

@blargly thoughts? Is the duplication a necessary evil until the directory code can live in the same repo? Or is publishing a package or using submodules worth it to avoid it?
How else do we ensure that schema changes to Organisation in the directory don't break publications because it's schema is elsewhere.
Discussions around SubmissionAPI/Directory alignment may affect decisions on this too.

2020-10-20 08:56 UTC, beforan commented on src/Publications/Publications/PublicationDbContext.cs
> +        public DbSet<Organisation> Organisations { get; set; }
sorry that's out of date. `DbQuery<>` is deprecated.

2020-10-20 08:57 UTC, beforan commented on src/Publications/Publications/Entities/Organisation.cs
> +    public class Organisation
Also, I notice this PR removes migrations. So is the Directory now responsible for the Publication entity? In which case I have the same concerns about that.

2020-10-20 10:10 UTC, beforan commented on src/Publications/Publications/Entities/Organisation.cs
> +    public class Organisation
Chatted with @blargly we'll leave the duplication for now, as we now have something of a roadmap for the Directory to resolve these issues with regards to the API as well as the other dependent services.

There will be work to undo this duplication on that roadmap, so it should hopefully be relatively shortlived, given the renewed focus on the API.

2020-10-20 21:43 UTC, beforan submitted a review, later dismissed

2020-11-17 14:49 UTC, Flemingjp requested changes

2020-11-17 14:49 UTC, Flemingjp commented on src/Publications/Publications/Services/PublicationService.cs
>          {
Is this method used anymore? If not remove it?

2020-11-17 15:45 UTC, Flemingjp approved these changes

2020-11-18 15:23 UTC, beforan approved these changes

2020-11-18 15:34 UTC, merged