Open sourcing the Biobanking Directory Codebase
biobankinguk/biobankinguk pull request #41
Opened 2020-10-30 11:07 UTC by Flemingjp

Open sourcing the Biobanking Directory Codebase into the monorepo. This includes the main Directory project and the supporting projects as well.

2020-10-30 11:16 UTC, JosephLavagna approved these changes

2020-10-30 16:37 UTC, shakisparki commented
PR is failing checks?

2020-11-02 11:48 UTC, beforan requested changes
In addition to comments on files:

- Imperial URW font files need removing. They should be privately deployed to relevant environments.
- FontAwesome fonts: need to ensure OFL 1.1 license text is nearby.
- Many image assets may want to move to private environment deployment.

2020-11-02 11:48 UTC, beforan commented on .azure/pipelines/build.dataseed.yml
> +- master
for now can we limit this to only run on file changes in paths for this project, or its dependencies, rather than every master push (e.g. directory only changes)

2020-11-02 11:48 UTC, beforan commented on .azure/pipelines/build.web.yml
> +  - master
limit triggering to appropriate paths

2020-11-02 11:48 UTC, beforan commented on .azure/pipelines/deploy.web.yml
> +# deployments are never triggered by ci
move this pipeline to a  private repo for deploying our instances.

2020-11-02 11:48 UTC, beforan commented on .azure/pipelines/templates/template.deploy.web.yml
> +# Manual trigger only
what is this file? it's not a devops pipeline template.

2020-11-02 11:48 UTC, beforan commented on src/.gitignore
> +## Ignore Visual Studio temporary files, build results, and
I don't think this `.gitignore` is doing anything for us that the one in the repo root isn't already.

Try deleting it, and then if there are new files git wants to track, instead add them either to the top level one if they are general, or to a `.gitignore` in `src/Directory/` if they are more specific

2020-11-02 11:48 UTC, beforan commented on src/Directory/Biobanks.Web/Error/FindDx/error.html
> +
this file should move to private repo for deployment

2020-11-02 11:48 UTC, beforan commented on src/Directory/Biobanks.Web/Error/error.html
> +
this file should be vastly genericised (unbranded).

an equivalent for TDCC will be needed in private environments repo

2020-11-17 10:19 UTC, Flemingjp commented
Closed - will pull across current codebase instead

2020-11-17 10:19 UTC, closed without merging