Open source API to GitHub
biobankinguk/biobankinguk pull request #42
Opened 2020-10-30 11:43 UTC by Flemingjp

Opensourcing the API into Github. Adding the `./Api` project and adding a initial .yml pipeline

2020-10-30 14:27 UTC, Flemingjp commented
This PR also removes the `DataLoader` from the API

2020-11-23 09:06 UTC, beforan requested changes

2020-11-23 09:06 UTC, beforan commented on .azure/pipelines/api.yml
> +    - 'ApiToGithub'
for now do whatever the directory pipelines do. Probably `master` or `*`, possibly PR triggers. We may want to revisit at a later date.

2020-11-23 09:08 UTC, beforan commented
Do we need to a do dependency license check, similar to what we did for the directory? Or was that already done?

I think we're unlikely to hit issues since these have fewer dependencies and are .NET Core, so more likely to be MIT or similar.

2020-11-23 09:11 UTC, Flemingjp commented
@beforan We need to check the licenses

2020-11-27 11:28 UTC, beforan commented
> @beforan We need to check the licenses

licenses are all fine

2020-11-30 11:12 UTC, beforan requested changes

2020-11-30 13:05 UTC, beforan requested changes

2020-11-30 13:05 UTC, beforan commented on src/Api/IdentityProvider/Properties/launchSettings.json
> +  "iisSettings": {
remove `iisSettings`

2020-11-30 13:05 UTC, beforan commented on src/Api/IdentityProvider/Properties/launchSettings.json
> +    "IIS Express": {
Remove the `IIS Express` profile.

This is a good reason for committing this file ;) to ensure everyone working on it runs it just under kestrel locally.

2020-11-30 13:05 UTC, beforan commented on src/Api/SubmissionApi/Properties/launchSettings.json
> +    "IIS Express": {
as in the other project

2020-11-30 15:02 UTC, beforan approved these changes

2020-12-01 09:55 UTC, blargly approved these changes

2020-12-01 10:12 UTC, merged