AB33843#: Net6
biobankinguk/biobankinguk pull request #436
Opened 2022-10-08 04:40 UTC by blargly

Upgraded project to Net 6 as a precursor to implementing identy on the new directory.

Replaced startup/program launch with modern startup free approach.

Keen to hear opinions on how program.cs should be organised.

2022-10-12 15:12 UTC, AndyRae commented on src/Submissions/Api/Api.csproj
> +    <TargetFramework>net6.0</TargetFramework>
Moving to 6 - might be an opportunity to use [ImplicitUsings](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#implicitusings);
Would be interested to hear opinions on effectively hiding many of the `using System;` directives, but would note in new 6 apps that this is enabled by default.

2022-10-14 14:19 UTC, beforan requested changes

2022-10-14 14:19 UTC, beforan commented on src/Submissions/Api/Api.csproj
> -    <TargetFramework>net5.0</TargetFramework>
need to make sure all other projects which target net5 are changed to net6 as well.

e.g. `Data`

2022-10-14 14:19 UTC, beforan commented on src/Submissions/Api/Program.cs
> +    .AddEntityFrameworkStores<BiobanksDbContext>();
Does `BiobanksDbContext` also need updating to inherit from `IdentityDbContext` for this to work?

(That is a desirable change at some point anyway)

2022-10-14 14:19 UTC, beforan commented on src/Submissions/Api/Program.cs
> +builder.Services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
`IdentityUser` should be `ApplicationUser` or whatever the custom user class is called. I know it's been copied over to Submissions already.

2022-10-14 14:19 UTC, beforan commented on src/Submissions/Api/Program.cs
> +builder.Services.AddRazorPages();
Don't think Submissions uses Razor Pages, so don't add them

2022-10-14 14:19 UTC, beforan commented on src/Submissions/Api/Program.cs
> +app.MapRazorPages();
As above, don't believe this is needed.

2022-10-14 14:19 UTC, beforan commented on src/Submissions/Api/appsettings.json
> +"Microsoft.AspNetCore":  "Warning",
This seems wrong... pretty sure it should still be inside a logging section?

2022-10-14 14:20 UTC, beforan commented on src/Submissions/Api/Api.csproj
> +    <TargetFramework>net6.0</TargetFramework>
I would suggest as a starter for 10 we do what the net6 templates do by default for this.

But yeah, agree could be useful going forwards

2022-10-14 14:22 UTC, beforan commented on src/Submissions/Api/Program.cs
> +builder.Services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
I appreciate that the actual identity config is still to come in a later PR, but using the wrong class here at this stage might cause undesirable extra migrations to get the right Users table schema.

2022-10-20 14:19 UTC, AndyRae submitted a review, later dismissed

2022-10-20 14:36 UTC, AndyRae approved these changes

2022-10-20 14:42 UTC, MoizIqbal97 approved these changes

2022-10-20 14:50 UTC, merged