AB#80183: Clone email services
biobankinguk/biobankinguk pull request #458
Opened 2022-10-20 14:26 UTC by AndyRae

## Overview

Clones the email services from SIMUN as close as possible.

2022-10-21 13:14 UTC, MoizIqbal97 submitted a review, later dismissed

2022-10-27 15:33 UTC, MoizIqbal97 submitted a review, later dismissed

2022-10-28 10:58 UTC, beforan requested changes

2022-10-28 10:58 UTC, beforan commented on src/Submissions/Api/Services/EmailSender/LocalDiskEmailSender.cs
> +        public async Task SendEmail<TModel>(List<EmailAddress> toAddresses, string viewName, TModel model)
Can you update this file to be based on the version from [Hutch](https://github.com/HDRUK/hutch/blob/main/app/HutchManager/Services/EmailSender/LocalDiskEmailSender.cs) please.

It's more up to date and has some niceties around supporting home paths, and creating the target directory if it's not present :)

2022-10-28 12:50 UTC, beforan approved these changes

2022-10-28 12:51 UTC, MoizIqbal97 approved these changes

2022-10-28 12:51 UTC, merged