AB#76206: Home controller
biobankinguk/biobankinguk pull request #463
Opened 2022-11-01 11:50 UTC by MoizIqbal97

Adds ConfigKey string varliables
Contact Controller moved out to its own Controller
Home Controller added
Config Service updated to use IMemoryCache
_FeedbackMessage view ported

2022-11-01 13:54 UTC, AndyRae approved these changes

2022-11-01 13:54 UTC, AndyRae commented on src/Submissions/Api/Controllers/HomeController.cs
> +      //  public ActionResult Cookies() => View(); TODO copy views over
If we're not adding the home / contact views at this point, it's worth adding a PBI to make sure we do pick them up.

2022-11-02 16:12 UTC, dcl10 requested changes

2022-11-02 16:12 UTC, dcl10 commented on src/Submissions/Api/Controllers/ContactController.cs
> +        //private readonly IEmailService _emailService; //TODO: Email Service has not be ported yet
⛏️ If you're not using the commented code in this file anymore, just delete it

2022-11-02 16:12 UTC, dcl10 commented on src/Submissions/Api/Controllers/HomeController.cs
> +        public async Task<IActionResult> IndexAsync()
Does this not need a `[HttpGet]` decorator?

2022-11-02 16:12 UTC, dcl10 commented on src/Submissions/Api/Controllers/HomeController.cs
> +      //  public ActionResult Cookies() => View(); TODO copy views over
⛏️ remove if not needed

2022-11-02 16:31 UTC, MoizIqbal97 commented on src/Submissions/Api/Controllers/HomeController.cs
> +        public async Task<IActionResult> IndexAsync()
We are inheriting from the `Controller` class, the convention for this is `/<ControllerName>/<ActionMethodName>` .
Index method is a special action name where it is served from just `/<ControllerName>/` 

The decorates are only used for API controllers which uses the `ControllerBase` class and the `[ApiController]` attribute

(answer plagarised from @beforan XD )

2022-11-02 16:35 UTC, dcl10 approved these changes

2022-11-03 09:10 UTC, AndyRae approved these changes

2022-11-03 09:21 UTC, merged