AB#76209: Pages Admin Controller
biobankinguk/biobankinguk pull request #480
Opened 2022-11-14 16:39 UTC by MoizIqbal97

Port over Page Controller and subsequent Views, Model and Script

2022-11-14 20:35 UTC, blargly approved these changes

2022-11-15 10:13 UTC, beforan requested changes

2022-11-15 10:13 UTC, beforan commented on src/Submissions/Api/Api.csproj
> +    <PackageReference Include="MvcSiteMapProvider.MVC5.Core" Version="4.6.26" />
Don't add this at this time, we need to figure out a Core compatible solution to it separately.

2022-11-15 10:13 UTC, beforan commented on src/Submissions/Api/Api.csproj
> +    <PackageReference Include="Microsoft.AspNet.Web.Optimization" Version="1.1.3" />
You can't add this, it's an old framework asp.net package.

(see the `Microsoft.AspNet` prefix; not `Microsoft.AspNetCore`)

remove it and then we'll have to fix whatever code was wanting it

2022-11-15 10:13 UTC, beforan commented on src/Submissions/Api/Api.csproj
> +    <Folder Include="Scripts\Bundles\" />
not sure what this is included for?

2022-11-15 10:13 UTC, beforan commented on src/Submissions/Api/App_Start/BundleConfig.cs
> +    {
You can't use `BundleConfig.cs` in Core.

Remove this file.

If you want JS to work you need to look at the Framework directory's `BundleConfig.cs` to find out what files were included in the bundle you want, then add those files MANUALLY to the page.

e.g.

the script bundle in this file is called `~/bundles/pageadmin` but references multiple actual js files, so you'd have to add the following to the page:

```html
<script src="~/Scripts/Directory/directory-pages-admin.js"></script>
<script src="~/Scripts/bootbox.js"></script> <!-- for however many bootbox scripts there are -->
<script src="~/Scripts/Directory/directory-refdata-utility.js"></script>
```

2022-11-15 10:13 UTC, beforan commented on src/Submissions/Api/App_Start/BundleConfig.cs
> +    {
Alternatively wait for me to sort out the bundles in a Core way.

2022-11-15 10:13 UTC, beforan commented on src/Submissions/Api/Config/ConfigKey.cs
> +        public const string ShowPreservationPercentageBool = "true";
this file is a list of keys. "true" is not going to be the key for this config settings. it might be the value.

I suggest looking at the framework directory code to see what the key should be.

2022-11-15 10:13 UTC, beforan commented on src/Submissions/Api/Config/ConfigKey.cs
> +        public const string ShowPreservationPercentageBool = "true";
presumably something similar to the others, e.g. `site.display.showpreservationpercentagebool`

though I really hope it doesn't have `bool` on the end, that's not good naming practice.

2022-11-15 10:13 UTC, beforan commented on src/Submissions/Api/Controllers/Submissions/PagesAdminController.cs
> +using MvcSiteMapProvider.Web.Mvc.Filters;
I wouldn't expect a controller to reference MVC Sitemap, but if you're unsure how to take out what's using it, give me a shout. We can't use it as is in Core

2022-11-15 10:23 UTC, beforan commented on src/Submissions/Api/Api.csproj
> +    <PackageReference Include="MvcSiteMapProvider.MVC5.Core" Version="4.6.26" />
AB#84952 raised to track

2022-11-15 11:32 UTC, beforan approved these changes

2022-11-25 14:13 UTC, AndyRae approved these changes

2022-11-28 10:33 UTC, merged