AB#76219: Profile controller
biobankinguk/biobankinguk pull request #483
Opened 2022-11-16 16:01 UTC by MoizIqbal97

Ports over profile controller and views

2022-11-28 12:11 UTC, AndyRae requested changes

2022-11-28 12:11 UTC, AndyRae commented on src/Submissions/Api/Services/Directory/BiobankService.cs
> +        public async Task<IEnumerable<OrganisationServiceOffering>> ListBiobankServiceOfferingsAsync(int biobankId)
Can now remove these from the `BiobankReadService` in submissions as well 🙂

2022-11-28 12:13 UTC, AndyRae commented on src/Submissions/Api/Models/Biobank/CapabilityModel.cs
> +namespace Biobanks.Submissions.Api.Models.Biobank
Looking through - doesn't look like ProfileController uses anything in `Biobanks.Submissions.Api.Models.Biobank` - so this might be move the one in `Models/Profile/CapabilityModel` instead of this one.

2022-11-28 14:41 UTC, AndyRae approved these changes

2022-11-29 08:52 UTC, blargly approved these changes

2022-11-29 08:55 UTC, merged