AB#76213: Super User Controller
biobankinguk/biobankinguk pull request #485
Opened 2022-11-29 11:07 UTC by MoizIqbal97

Ports ove rthe super user controller

2022-11-29 13:35 UTC, AndyRae requested changes

2022-11-29 13:35 UTC, AndyRae commented on src/Submissions/Api/Controllers/Directory/SuperUserController.cs
> +    private readonly IBiobankWriteService _biobankWriteService;
Can remove the write service dependency - doesn't appear to be used

2022-11-29 13:39 UTC, AndyRae commented on src/Submissions/Api/Controllers/Directory/SuperUserController.cs
> +    private readonly IBiobankWriteService _biobankWriteService;
```suggestion
```

2022-12-02 12:01 UTC, blargly approved these changes

2022-12-02 13:02 UTC, AndyRae approved these changes

2022-12-02 13:09 UTC, merged