AB#84363: Biobanks Controller
biobankinguk/biobankinguk pull request #488
Opened 2022-12-02 10:47 UTC by MoizIqbal97

Ports over the Biobanks Controller and Views
Configure Admin areas

2022-12-02 12:29 UTC, AndyRae approved these changes

2022-12-02 12:29 UTC, AndyRae commented on src/Submissions/Api/Models/Biobank/BiobankAdminsModel.cs
> +using Biobanks.Submissions.Api.Models.Shared;
This could go in `Area/Admin/Models` maybe?  
As far as I can tell this isn't a shared model - but solely used by the admin area Biobank controller, so would make sense to group it all in the area where possible.

Not crucial though

2022-12-02 13:00 UTC, MoizIqbal97 commented on src/Submissions/Api/Models/Biobank/BiobankAdminsModel.cs
> +using Biobanks.Submissions.Api.Models.Shared;
Done :)

2022-12-02 13:02 UTC, AndyRae submitted a review, later dismissed

2022-12-02 14:38 UTC, beforan requested changes

2022-12-02 14:38 UTC, beforan commented on src/Submissions/Api/Config/SitePropertiesOptions.cs
> +    public string EmailFromName { get; init; } = "EmailFromName";
this should be coming from email sender options, we don't need to add it to siteproperties as well.

2022-12-02 14:38 UTC, beforan commented on src/Submissions/Api/Config/SitePropertiesOptions.cs
> +    public string EmailFromAddress { get; init; } = "EmailFromAddress";
same

2022-12-02 14:38 UTC, beforan commented on src/Submissions/Api/Area/Admin/Controllers/BiobankController.cs
> +public class BiobankController : Controller
- Controller names should be plural - change the controller and file name to `BiobanksController`
- Controllers inside Areas need annotating with the Area as per [this](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-7.0#associate-the-controller-with-an-area)
- Can we use the default conventional path for Areas as per [this](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-7.0#area-folder-structure)? (we are currently using `Area` not `Areas` e.g. `Area/Admin/Controllers...` - change to `Areas/Admin/Controllers...`)

2022-12-02 14:38 UTC, beforan commented on src/Submissions/Api/Models/Shared/InviteRegisterEntityAdminModel.cs
> +  public string ControllerName { get; set; }
this will eventually break now that we're adding areas... since controllername strictly speaking won't be enough.

2022-12-02 14:38 UTC, beforan commented on src/Submissions/Api/Program.cs
> +    name: "MyArea",
`MyArea` is a bit tutorially? I would probably call it `AreasDefault` as it's doing a default catch all for area routes, as opposed to the non area routes below, or specific matches (which we don't have any of...yet)

2022-12-02 15:52 UTC, beforan requested changes

2022-12-02 15:52 UTC, beforan commented on src/Submissions/Api/Areas/Admin/Controllers/BiobanksController.cs
> +namespace Biobanks.Submissions.Api.Area.Admin.Controllers;
namespace doesn't match the folders now 😅
```suggestion
namespace Biobanks.Submissions.Api.Areas.Admin.Controllers;
```

2022-12-02 15:52 UTC, beforan commented on src/Submissions/Api/Views/Shared/Emails/ExistingUserRegisterEntityAdminInvite.cshtml
> +var emailSubject = HostEnvironment.IsDevelopment()
this needs to be assigned to `ViewBag.Subject` if you want it to set the subject line.
```suggestion
ViewBag.Subject = HostEnvironment.IsDevelopment()
```

2022-12-02 15:52 UTC, beforan commented on src/Submissions/Api/Views/Shared/Emails/ExistingUserRegisterEntityAdminInvite.cshtml
> +Content-Type: text/plain; charset=utf-8
```suggestion
```
we don't do this in the view anymore

2022-12-02 15:52 UTC, beforan commented on src/Submissions/Api/Views/Shared/Emails/NewUserRegisterEntityAdminInvite.cshtml
> +Content-Type: text/plain; charset=utf-8
```suggestion
```

2022-12-02 15:52 UTC, beforan commented on src/Submissions/Api/Views/Shared/Emails/NewUserRegisterEntityAdminInvite.cshtml
> +	var emailSubject = HostEnvironment.IsDevelopment()
```suggestion
	ViewBag.Subject = HostEnvironment.IsDevelopment()
```

2022-12-02 15:52 UTC, beforan commented on src/Submissions/Api/Views/Shared/Emails/NewUserRegisterEntityAdminInvite.cshtml
> +You've been invited to become an admin for @Html.Raw(ViewBag.Entity) at the @directoryName.
have any of these views been tested? I'm pretty sure 99% of `ViewBag` usage in all the email views should have been changed to Model properties. Because `EmailService` builds a model and assigns values to properties on that model, but the views then never use said model and use ViewBag instead (on which no values have been set!)

2022-12-02 15:52 UTC, beforan commented on src/Submissions/Api/Views/Shared/Emails/NewUserRegisterEntityAdminInvite.cshtml
> +You've been invited to become an admin for @Html.Raw(ViewBag.Entity) at the @directoryName.
compare to e.g. Decsys (or any of our other projects using this email pattern):

https://github.com/decsys/decsys/blob/main/app/Decsys/Views/Emails/AccountConfirmation.cshtml

there it uses the model and the property on the model.

2022-12-02 15:52 UTC, beforan commented on src/Submissions/Api/Areas/Admin/Controllers/BiobanksController.cs
> +        return Json(new
I'm not sure what the `JsonResult`/`Json()` combo are giving us here? they feel a bit .NET Framework MVC ish.

The conventional way to return some JSON in Core is surely just `ActionResult<T>` and then `return objectOfTypeT` or if necessary `IActionResult` and `return Ok(object)`?

Unless that only holds true for ApiControllers and not MVC ones?

2022-12-02 15:52 UTC, beforan commented on src/Submissions/Api/Models/Shared/InviteRegisterEntityAdminModel.cs
> +  public string ControllerName { get; set; }
the actual usage of this seems to be in JS, so can we just have a noisy `TODO` to come back and join the dots when we fix the JS urls?

2022-12-05 15:46 UTC, beforan approved these changes

2022-12-05 15:50 UTC, AndyRae approved these changes

2022-12-05 15:51 UTC, merged