AB#84951: Javascript bundling
biobankinguk/biobankinguk pull request #498
Opened 2022-12-16 13:38 UTC by AndyRae

## Overview

Bundles the Javascript files in the core6 app, to be used in the frontend.

## Notes

- Obviously a large PR, so the main file to pay attention to is `src/submissions/api/bundleconfig.json` where the bundles are created.
- JS in `Frontend/js` is organised by pages / areas, with ADAC rename to Admin on a directory basis. 
- The bundler minifier does not handle the nullish coalescing operator `??` & `?`, see [issues](https://github.com/madskristensen/BundlerMinifier/issues?q=is%3Aissue+is%3Aopen+operator). So minifying has been turned off for these files that use them, this is mostly Admin (ADAC) code.
- Adds the script template to the existing views in the Directory, for ease of porting over these views. No tags are added to the existing views in the core app.
- Packages not available in npm have been vendored in `Frontend/vendor`

2022-12-16 15:54 UTC, dcl10 submitted a review, later dismissed

2022-12-22 10:56 UTC, beforan requested changes
My comments aren't exhaustive, but there are a couple of common themes to address throughout.

1. The minifier not supporting `??` isn't a problem in and of itself; not minifying is a sensible fix
  - however in practice for us it exposes a real issue: IE support
  - There's a reason the eslint config this PR adds specifies es5. All files should (manually because we don't have babel or similar in this project) be es5 so that they work in IE.
  - This means no arrow functions, no const, no let, no template strings and no nullish coalescing/propragation etc.
  - The code obviously previously should have adhered to that, but sometimes new code introduced broke it
  - Now we actually have linter config / js project code managed ina. somewhat modern way, we can better keep an eye on this, so this PR is an opportunity to fix these.
2. files appearing in more than one bundle.
  - I don't think in any case we should double-bundle source if possible. If two pages need a file, both pages should include that file's bundle, as opposed to the file being present in both page's bundles.
  - shared files should be bundled as high up the chain as makes sense. If they're light, and "safe" they should be in the layout bundle. If they're heavy, or unsafe, they should be in a bundle specific to a set of pages only (e.g. the markdown editor). If they're only used on a single page, they can go into a page bundle.
3. The source uses both `pages/` and `areas/` paths, but they seem to serve the same purpose from the perspective of logical organisation (e.g. even the `pages/` files are actually grouped by area/controller anyway); please consolidate into one or the other.

In summary:
- fix es5 errors throughout
- enable minifying hopefully in light of that
- don't double bundle files - any single source file should only be in one bundle
- shared files should be bundled as broadly as is sensible (balancing need vs bundle size)
- eliminate either `pages/` or `areas/`

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/appsettings.json
> +    "Default": "Server=localhost;Database=Biobanks;MultipleActiveResultSets=true;User ID=SA;Password=Password#1;",
this looks like a connection string specific to your machine?

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/node_modules/typeahead.js/dist/typeahead.bundle.min.js"
typeahead is already in the layout bundle

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/node_modules/typeahead.js/dist/typeahead.bundle.min.js",
typeahead is already in the layout bundle

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +    "minify": { "enabled": false },
curious what the minification problem is with this one?

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/js/shared/associated-data-admin.js"
if this file is actually shared, it shouldn't be in a per page bundle - pages which need it should include it from a shared bundle

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +    "inputFiles": ["Frontend/js/shared/associated-data-admin.js"],
as above, make a single bundle for this file and use it on both pages

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/Frontend/js/areas/Biobank/submissions.js
> +        { biobankId: $btn.data("biobank-id") }, data => {
arrow functions don't work in IE. linter should complain

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +    "minify": { "enabled": false },
curious what the minifcation issue is. this file needs es5 fixes anyway

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/js/shared/registerentity-admin-viewmodel.js"
if this is shared it shouldn't be in a per page bundle; the page should include via a shared bundle instead.

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/js/shared/diagnosis-type-ahead.js",
if this is shared it shouldn't be in a per page bundle.

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/js/shared/registerentity-funder-viewmodel.js",
if this is shaed it shouldn't be in a per page bundle. (if it's only used by this page, which seems likely, then move the file)

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/js/shared/registerentity-admin-viewmodel.js",
this is used by more than one page, it shouldn't be in multiple bundles.

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/Frontend/js/areas/Admin/adac-disease-statuses.js
> +      ? diseaseStatus.OtherTerms.split(",").map((item) => item.trim())
arrow functions don't work in es5

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/Frontend/js/areas/Admin/adac-disease-statuses.js
> +          (item) => item.Id === JSON.parse($("#ass-data-select").val()).Id
arrow functions don't work in es5

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/Frontend/js/areas/Admin/adac-disease-statuses.js
> +                      .map((item) => `<li>${item.Name}</li>`)
no es5 arrow functions

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/Frontend/js/areas/Admin/adac-disease-statuses.js
> +                      .map((item) => `<li>${item.Name}</li>`)
or template strings

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +    "minify": { "enabled": false },
curious on the issue here? However this file has a lot of es5 issues (arrow functions, template strings). The linter should catch them.

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +    "minify": { "enabled": false },
minification issues? didn't spot any es5 issues in this file (at a glance) so curious.

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +    "minify": { "enabled": false },
didn't spot es5 issues in here, so what's the minification issue?

2022-12-22 10:56 UTC, beforan commented on src/Submissions/Api/bundleconfig.json
> +    "minify": { "enabled": false },
same again, what's the issue as I can't spot it?

2023-01-03 14:03 UTC, AndyRae commented on src/Submissions/Api/bundleconfig.json
> +    "minify": { "enabled": false },
Line 516 in `collection-sample-sets.js` for custom knockout validation rules:

```
$(function () {
  ko.validation.rules["mustEqual"] = {
	validator(val, otherVal) {
	  return val === otherVal;
	},
}
```

Should be:
```
$(function () {
  ko.validation.rules["mustEqual"] = {
	validator: function(val, otherVal) {
	  return val === otherVal;
	},
}
```

2023-01-03 14:35 UTC, AndyRae commented on src/Submissions/Api/appsettings.json
> +    "Default": "Server=localhost;Database=Biobanks;MultipleActiveResultSets=true;User ID=SA;Password=Password#1;",
Removed

2023-01-03 14:35 UTC, AndyRae commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/node_modules/typeahead.js/dist/typeahead.bundle.min.js"
Removed

2023-01-03 14:36 UTC, AndyRae commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/js/shared/associated-data-admin.js"
Moved to a shared bundle.

2023-01-03 14:36 UTC, AndyRae commented on src/Submissions/Api/bundleconfig.json
> +    "inputFiles": ["Frontend/js/shared/associated-data-admin.js"],
Moved to a shared bundle.

2023-01-03 14:38 UTC, AndyRae commented on src/Submissions/Api/bundleconfig.json
> +    "minify": { "enabled": false },
The problem is actually in producing the source map, and not minifying. So have turned off the source map for the bundles that produce errors, and turned minify back on.

2023-01-04 11:10 UTC, AndyRae commented on src/Submissions/Api/Frontend/js/areas/Admin/adac-disease-statuses.js
> +                      .map((item) => `<li>${item.Name}</li>`)
Updated

2023-01-04 11:10 UTC, AndyRae commented on src/Submissions/Api/Frontend/js/areas/Admin/adac-disease-statuses.js
> +          (item) => item.Id === JSON.parse($("#ass-data-select").val()).Id
Updated

2023-01-04 11:10 UTC, AndyRae commented on src/Submissions/Api/Frontend/js/areas/Admin/adac-disease-statuses.js
> +      ? diseaseStatus.OtherTerms.split(",").map((item) => item.trim())
Updated

2023-01-04 11:11 UTC, AndyRae commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/js/shared/registerentity-admin-viewmodel.js",
Updated - moved to its own bundle.

2023-01-04 11:11 UTC, AndyRae commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/js/shared/registerentity-funder-viewmodel.js",
Updated the bundle.

2023-01-04 13:42 UTC, AndyRae commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/js/shared/diagnosis-type-ahead.js",
Updated - was only needed as a page bundle so moved the file.

2023-01-04 13:42 UTC, AndyRae commented on src/Submissions/Api/bundleconfig.json
> +      "Frontend/js/shared/registerentity-admin-viewmodel.js"
Updated - moved to a shared bundle.

2023-01-04 13:42 UTC, AndyRae commented on src/Submissions/Api/Frontend/js/areas/Biobank/submissions.js
> +        { biobankId: $btn.data("biobank-id") }, data => {
Updated to ES5

2023-01-09 11:02 UTC, beforan approved these changes

2023-01-09 11:27 UTC, merged