Move RefData Controller to Api Controller
biobankinguk/biobankinguk pull request #50
Opened 2020-11-20 12:20 UTC by Flemingjp

This is a rebase of #43 onto the new Open Source Directory branch.

**This PR currently merges into `oss-directory` to make the changes clearer - at time of merge it most likely wants to merge into master**

2020-11-20 12:22 UTC, Flemingjp commented
Reminded of https://github.com/biobankinguk/biobankinguk/pull/43#discussion_r525047679

2020-11-23 17:00 UTC, shakisparki commented
> Reminder of [#43 (comment)](https://github.com/biobankinguk/biobankinguk/pull/43#discussion_r525047679)

Resolved

2020-12-07 13:59 UTC, beforan requested changes

2020-12-07 13:59 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/AccessConditionsController.cs
> +        public async Task<IHttpActionResult> EditAccessConditionAjax(AccessConditionModel model)
also the signature and routing needs changing to take the `id` in the url, to make it RESTful

2020-12-07 13:59 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/AccessConditionsController.cs
> +        public async Task<IHttpActionResult> EditAccessConditionAjax(AccessConditionModel model)
and the verb should be PUT

2020-12-07 13:59 UTC, beforan commented on src/Directory/Biobanks.Web/Scripts/ADAC/adac-access-conditions.js
> +        var url = `/api/AccessConditions/${action}AccessConditionAjax`;
also, can we put the url in one place, probably in a class property

2020-12-07 13:59 UTC, beforan commented on src/Directory/Biobanks.Web/Scripts/ADAC/adac-access-conditions.js
> +        $.post("/api/AccessConditions/EditAccessConditionAjax?sortOnly=true",
can we have a sort endpoint?

something like:
- `/api/<Resource>/sort`
- `/api/<Resource>/<id>/move`
- `/api/<Resource>/<id>/move/<new position>`

2020-12-07 13:59 UTC, beforan commented on src/Directory/Biobanks.Web/Scripts/ADAC/adac-access-conditions.js
> +        var url = `/api/AccessConditions/${action}AccessConditionAjax`;
the behaviour change needs to be as follows:

instead of POSTing the model (id and description?) to either `Add<X>` or `Edit<X>`, we need to:

- If "Add", POST to `/api/<Resource>` with the payload as it is now, I guess
- If "Edit", PUT at `/api/<Resource>/<id>` with the payload as it is now. But this'll mean getting the id and using it in the url

2020-12-07 13:59 UTC, beforan commented on src/Directory/Biobanks.Web/App_Start/WebApiConfig.cs
> +                routeTemplate: "api/{controller}/{action}"
If we add a `sort` endpoint as suggested below, there will be action endpoints on otherwise RESTful resources. I would suggest using [Attribute-based Routing](https://docs.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/attribute-routing-in-web-api-2), to cover cases that stray from the default route template of `api/<controller>/<id>?`

It's clearer, more flexible and closer to ASP.NET Core's default conventions.

2020-12-07 13:59 UTC, beforan commented on src/Directory/Biobanks.Web/Views/ADAC/AnnualStatisticGroups.cshtml
> +                  data-update-action="/api/AnnualStatisticGroups/EditAnnualStatisticGroupAjax"
wait, the Views have data attributes with the URLs but the JS never uses them? Amazing.

That's the other option; put the URL here (only one URL though now of course, because it's just the resource endpoint `/api/<Resource>` in `data-resource-url` or something.

What are the Success URLs about? feedback? Where are the routes for those? still on `ADACController`? That doesn't seem right...

2020-12-07 13:59 UTC, beforan commented on src/Directory/Biobanks.Web/Web.config
> +    <add key="RefDataApiUrl" value="https://localhost:44300/"/>
what needs this? This app never uses an external API for ref data.

2020-12-07 13:59 UTC, beforan commented on src/Directory/Services/BiobankWriteService.cs
> +            await _materialTypeRepository.DeleteAsync(materialType.MaterialTypeId);
is this a bug fix?

2020-12-07 14:04 UTC, beforan commented
The point of this is not to just move the methods from `ADACController`, though that is a good move anyway, but to make a REST API for ref data that the other systems can also use as necessary, as well as the Directory UI. So it should follow modern API standards in the way it behaves (e.g. HTTP VERBs, not action POST endpoints).

Also I really hate that there's like 30 almost identical `.js` files... but we can't really confidently fix that nicely til we fix frontend bundling. So it'll have to wait. But we really should have one `ref-data-admin-view.js` and you just give it slightly differently shaped payloads and different endpoints (read from the view).

2020-12-09 16:47 UTC, shakisparki commented on src/Directory/Biobanks.Web/ApiControllers/AccessConditionsController.cs
> +        public async Task<IHttpActionResult> EditAccessConditionAjax(AccessConditionModel model)
@beforan For the PUT controller, model already contains an Id, so which signature is best here?

EditAccessConditionAjax(int id, [FromBody]string Description, [FromBody]int SortOrder)

EditAccessConditionAjax(int id, AccessConditionModel model)

EditAccessConditionAjax(AccessConditionModel model)

2020-12-09 17:05 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/AccessConditionsController.cs
> +        public async Task<IHttpActionResult> EditAccessConditionAjax(AccessConditionModel model)
I was thinking `(int id, Model model)`

I realise we technically duplicate the `id` then. Technically we should probably use a different model that doesn't include `id` but i'm not super fussed. The `id` param is the one to use though, not the model one

2020-12-09 17:24 UTC, shakisparki commented on src/Directory/Biobanks.Web/Views/ADAC/AnnualStatisticGroups.cshtml
> +                  data-update-action="/api/AnnualStatisticGroups/EditAnnualStatisticGroupAjax"
Yes, the URLs are for feedback. Where do you expect them to be? 
Isn't the feedback given dependent on the application not the API?
and if not in ADACController, where else could it reside? in the ApiController?

2020-12-14 14:02 UTC, beforan requested changes

2020-12-14 14:03 UTC, beforan commented on src/Directory/Biobanks.Web/Views/ADAC/AnnualStatisticGroups.cshtml
> +                  data-update-action="/api/AnnualStatisticGroups/EditAnnualStatisticGroupAjax"
I've reviewed the way this currently works and i see that it is needed. I can't think of a better place to put it right now; definitely not the ApiController, so we'll leave it.

2020-12-28 21:11 UTC, shakisparki commented on src/Directory/Biobanks.Web/Scripts/ADAC/adac-access-conditions.js
> +    this.modalModeEdit = "Update";
some already used update, and others edit. Simply easier for me to make them similar for easier modification

2020-12-28 21:18 UTC, shakisparki commented on src/Directory/Services/BiobankWriteService.cs
> +            await _materialTypeRepository.DeleteAsync(materialType.MaterialTypeId);
didn't seem to work as before

2021-01-05 10:42 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/CollectionPointController.cs
> +        {
Should this endpoint just be named `Delete`

2021-01-05 10:42 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/RegistrationReasonController.cs
> +        {
Is it cleaner and/or clearer to use `using RegistrationReasonModel = Biobanks.Web.Models.Shared.RegistrationReasonModel`

2021-01-05 10:42 UTC, Flemingjp commented on src/Directory/Biobanks.Web/ApiControllers/ServiceOfferingController.cs
> +        {
Same as above

`using ServiceOfferingModel = Biobanks.Web.Models.Shared.ServiceOfferingModel;`

2021-01-05 14:14 UTC, beforan requested changes

2021-01-05 14:14 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/AssociatedDataProcurementTimeFrameController.cs
> +                ModelState.AddModelError("AssociatedDataProcurementTimeFrame", "That Associated Data Procurement Time Frame already exists!");
This is an odd error message. This is a PUT on a resource id, which suggests it should be used for editing the resource with that id. In which case I would hope it does exist.

Or do we create at specific id's? (I don't think so; we also have a POST action for creating).

Is just the error message wrong? Or the actual validation method?

2021-01-05 14:14 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/AssociatedDataProcurementTimeFrameController.cs
> +                ModelState.AddModelError("AssociatedDataProcurementTimeFrame", "That Associated Data Procurement Time Frame already exists!");
Not sure if this affects other controllers' PUT methods too

2021-01-05 14:14 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/AssociatedDataProcurementTimeFrameController.cs
> +                ModelState.AddModelError("AssociatedDataProcurementTimeFrame", "The Display Name field is required.");
Why can't these be done by annotations on the model? Seems a little odd...
```
[Required]
[MinLength(10)]
```

2021-01-05 14:14 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/AssociatedDataProcurementTimeFrameController.cs
> +        public async Task<IHttpActionResult> Put(int id, Models.Shared.AssociatedDataProcurementTimeFrameModel model)
prefer using statements to inline namespacing, unless clarifying an ambiguity between two or more identically named (but differently namespaced) types in use in the same file.

`using Models.Shared;`

especially since the type is used multiple times.

2021-01-05 14:14 UTC, beforan commented on src/Directory/Biobanks.Web/Scripts/ADAC/adac-access-conditions.js
> +    this.modalModeEdit = "Update";
happy with making them consistent, didn't realise they didn't all use Edit ;)

2021-01-05 14:14 UTC, beforan commented on src/Directory/Biobanks.Web/Scripts/ADAC/adac-access-conditions.js
> +                 "/Sort/" + $(triggerRow.node).data('access-condition-id'),
sorry, this route'll need changing as the controllers change

2021-01-05 16:55 UTC, shakisparki commented on src/Directory/Biobanks.Web/ApiControllers/AssociatedDataProcurementTimeFrameController.cs
> +        public async Task<IHttpActionResult> Put(int id, Models.Shared.AssociatedDataProcurementTimeFrameModel model)
that is the case in this file (ambiguity). But I'll use the namespace on the other other one as it appears only once

2021-01-06 09:31 UTC, beforan commented on src/Directory/Biobanks.Web/ApiControllers/AssociatedDataProcurementTimeFrameController.cs
> +                ModelState.AddModelError("AssociatedDataProcurementTimeFrame", "That Associated Data Procurement Time Frame already exists!");
oh it doesn't mean the record already exists (by id), it means the description/name/value is the same as another record's? that makes more sense, and can be left.

2021-01-06 09:42 UTC, beforan approved these changes

2021-01-06 09:57 UTC, beforan approved these changes

2021-01-06 09:57 UTC, JosephLavagna approved these changes

2021-01-06 10:01 UTC, merged