AB#89361: controller testing analytics controller
biobankinguk/biobankinguk pull request #526
Opened 2023-01-31 10:58 UTC by MoizIqbal97

Fixes to display analytics page

2023-01-31 14:33 UTC, AndyRae requested changes

2023-02-06 13:10 UTC, AndyRae commented
Note - analytics controller now works without errors, but can't test further until analytics job is able to run ([see docs](https://github.com/biobankinguk/biobankinguk/wiki/Worker-Jobs#analytics-job))
Block is that `GoogleAnalyticsViewId` is neeced

2023-03-01 11:17 UTC, AndyRae approved these changes

2023-03-01 11:23 UTC, blargly approved these changes

2023-03-01 11:26 UTC, merged