AB#82665: Submissions structure merging
biobankinguk/biobankinguk pull request #527
Opened 2023-01-31 11:40 UTC by AndyRae

## Overview

Merges:
- Entities project into Data
- AzureStorage project into Core.

2023-02-01 08:17 UTC, MoizIqbal97 approved these changes

2023-02-02 09:33 UTC, beforan requested changes
I think some of the moved classes from `Entities` are in fact entities and should therefore end up in the `Entities/` folder in the `Data` project.

2023-02-02 11:22 UTC, blargly approved these changes

2023-02-02 15:21 UTC, beforan approved these changes

2023-02-02 15:21 UTC, merged

2023-02-02 15:21 UTC, MoizIqbal97 approved these changes