AB#89381: Allow Block List
biobankinguk/biobankinguk pull request #530
Opened 2023-02-01 14:39 UTC by MoizIqbal97

Changes to fix Admin/RegistrationDomainRules/BlockAllowList

![image](https://user-images.githubusercontent.com/90258816/216072887-f70ba21e-5eba-4e31-b77f-c133a49e85b6.png)

2023-02-01 15:07 UTC, AndyRae commented on src/Submissions/Api/Frontend/js/pages/Admin/adac-blockallow-list.js
> +      "Are you sure you want to delete " + linkData.Value + "?",
Based on fixing the ref data patterns:

Does this work? (does the modal show the value of the rule?)
Fix is probably to lowercase if not:
```suggestion
      "Are you sure you want to delete " + linkData.value + "?",
```

And does it actually delete successfully? If not, again fix is lowercase on the linkData.id (line 104)

2023-02-02 09:55 UTC, beforan requested changes

2023-02-02 09:55 UTC, beforan commented on src/Submissions/Api/Startup/Web/ConfigureWebServices.cs
> +    AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
this is done globally in another PR, so i think can be removed from here
```suggestion
```

2023-02-02 10:20 UTC, AndyRae approved these changes

2023-02-02 10:33 UTC, merged