AB#89387: Admin registration requests
biobankinguk/biobankinguk pull request #534
Opened 2023-02-03 16:26 UTC by AndyRae

## Overview

Fixes the Admin area Requests controller, and the registration user journeys.

Mostly fixing the routing with areas, and a few email gotchas.

This is now working - users can register a request, have it approved, be sent the relevant emails, with correct links to activate their account.

2023-02-06 13:26 UTC, AndyRae commented on src/Submissions/Api/Areas/Admin/Controllers/RequestsController.cs
> +              Request.Scheme)
Essentially this is fetching the request protocol (`https`) - `getEncodedUrl` mistakenly fetched the entire url and sent a broken link.

2023-02-06 13:34 UTC, beforan requested changes

2023-02-06 13:34 UTC, beforan commented on src/Submissions/Api/Views/Shared/Emails/ResendConfirm.cshtml
> +	var emailFrom = String.Format(@"""{0}"" {1}",
this may not be necessary.

if it is, please use string interpolation over string.format if at all possible

2023-02-06 13:34 UTC, beforan commented on src/Submissions/Api/Views/Shared/Emails/ResendConfirm.cshtml
> +	var emailSubject = HostEnvironment.IsDevelopment()
90% sure this ternary is the wrong way round.

and actually, `IsDevelopment` is the wrong condition.

The desirable behaviour is that all non-prod environments include their environment.

It occurs to me it'd be much better to do this append in the Email Service somewhere (possibly even Email Sender) rather than in every single email.

2023-02-06 13:34 UTC, beforan commented on src/Submissions/Api/Views/Shared/Emails/ResendConfirm.cshtml
> +	var emailSubject = HostEnvironment.IsDevelopment()
(and, to be clear, prod should NOT include an environment in its subject line as that's kind of unprofessional leakage to customers)

2023-02-06 13:34 UTC, beforan commented on src/Submissions/Api/Views/Shared/Emails/ResendConfirm.cshtml
> +	var emailSubject = HostEnvironment.IsDevelopment()
actually, SargAssure's EmailSender does include this functionality: https://github.com/SargAssure/SargAssure/blob/6ceada559151dabb80f54b297c81375a38077cd8/app/SargAssure/Services/EmailSender/SendGridEmailSender.cs#L32

2023-02-06 13:35 UTC, beforan commented on src/Submissions/Api/Views/Shared/Emails/ResendConfirm.cshtml
> +	var emailSubject = HostEnvironment.IsDevelopment()
and so does SIMUN

2023-02-06 17:25 UTC, blargly approved these changes

2023-02-07 11:05 UTC, AndyRae commented on src/Submissions/Api/Views/Shared/Emails/ResendConfirm.cshtml
> +	var emailSubject = HostEnvironment.IsDevelopment()
Have removed this from all the emails templates - the email service does include this as well.

2023-02-08 14:21 UTC, beforan approved these changes

2023-02-10 10:01 UTC, blargly approved these changes

2023-02-10 10:10 UTC, merged