Automatically trust biobanks when have same email as network
biobankinguk/biobankinguk pull request #56
Opened 2020-11-24 15:28 UTC by JosephLavagna

- Automatically trust biobanks when they have the same contact/admin emails.
- Email is not sent out for those biobanks that are automatically approved.

2020-11-24 15:34 UTC, beforan requested changes

2020-11-24 15:34 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/NetworkController.cs
> +            List<String> networkEmails = new List<string>();
`var` pls. also lowercase primitives (`string` not `String`)

2020-11-24 15:34 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/NetworkController.cs
> +            List<String> biobankEmails = new List<string>();
as above

2020-11-25 09:40 UTC, beforan approved these changes

2020-11-25 13:19 UTC, blargly approved these changes

2020-11-25 16:17 UTC, merged