add about page for FIND
biobankinguk/biobankinguk pull request #57
Opened 2020-11-25 15:43 UTC by shakisparki

add about page with markdown configurable contents

2020-11-25 15:56 UTC, beforan commented on src/Directory/Data/Constants/ConfigKey.cs
> +        public const string AboutpageTitle = "site.aboutpage.title";
does the title get used anywhere?

2020-11-25 15:56 UTC, beforan commented on src/Directory/Biobanks.Web/Biobanks.Web.csproj
> +    <Content Include="Content\wordpress.json" />
what's this?

2020-11-25 15:57 UTC, shakisparki commented on src/Directory/Data/Constants/ConfigKey.cs
> +        public const string AboutpageTitle = "site.aboutpage.title";
absolutely forgot to take that out

2020-11-25 15:58 UTC, shakisparki commented on src/Directory/Biobanks.Web/Biobanks.Web.csproj
> +    <Content Include="Content\wordpress.json" />
that should not be there

2020-11-25 15:58 UTC, beforan requested changes

2020-11-25 15:58 UTC, beforan commented on src/Directory/Data/Migrations/Configuration.cs
> +The Foundation for Innovative New Diagnostics(FIND), a non - profit global health organization, supports activities and projects to improve diagnosis of infectious diseases in low - and middle - inco
this is environment specific content, it shouldn't be the default.

2020-11-25 15:59 UTC, beforan commented
is this functionality supposed to be able to be turned off (e.g. TDCC doesn't use it today)?

2020-11-25 16:11 UTC, shakisparki commented
> is this functionality supposed to be able to be turned off (e.g. TDCC doesn't use it today)?
@blargly ?
Is this something for now or for the extra work to be done later?

2020-11-25 17:54 UTC, beforan approved these changes

2020-11-27 08:46 UTC, blargly approved these changes

2020-11-27 09:00 UTC, merged