Removing Biobanks & BiobanksIds controllers from Directory and removing references in Analytics
biobankinguk/biobankinguk pull request #60
Opened 2020-11-27 17:00 UTC by bradthompson995

The Biobanks & BiobanksIds api controllers are no longer neccesary so this PR removes them for the directory code and also removes the API calls from Analytics. Analytics has been modified to access the DB via local functions. Previous changes to master have done this for publications so for consistency a similar approach was used for doing the same to Analytics.

2020-12-02 16:45 UTC, Flemingjp requested changes
Everything look good - just a question and small change suggestion that might be useful while we're here

2020-12-02 16:45 UTC, Flemingjp commented on src/Analytics/AzureFunctions/Startup.cs
Maybe just use an `sqldb-connection` string? I know this is copied from what I wrote in the Publications function, but the Directory now parses the connection string via its deployment pipeline. Changing to that way would keep the behaviour consistent across the repo.

2020-12-02 16:45 UTC, Flemingjp commented on src/Analytics/Analytics/Organisation.cs
> +using System;
Is this entity a temporary solution until we have a common `Entities` project?

2020-12-02 18:09 UTC, shakisparki commented on src/Analytics/Analytics/Organisation.cs
> +using System;
Yes it is

2020-12-03 09:50 UTC, Flemingjp commented on src/Analytics/AzureFunctions/Startup.cs
@shakisparki  Don't forget to amend the pipelines

2020-12-03 09:50 UTC, Flemingjp approved these changes

2020-12-09 15:04 UTC, beforan approved these changes

2020-12-09 15:04 UTC, beforan commented on src/Analytics/Services/GoogleAnalyticsReadService.cs
> +        private AnalyticsDbContext _ctx;
pretty sure this should be `readonly`; it's dependency injected and assigned in the constructor only?

2020-12-09 15:05 UTC, beforan requested changes
i misreviewed 😛 please resolve my comments 👍

2020-12-09 15:24 UTC, beforan approved these changes

2020-12-09 15:25 UTC, Flemingjp approved these changes

2020-12-09 15:34 UTC, merged