Documentation For Creating An Elastic Search Instance On Azure
biobankinguk/biobankinguk pull request #61
Opened 2020-11-30 09:25 UTC by Flemingjp

2020-11-30 09:31 UTC, blargly submitted a review, later dismissed

2020-11-30 11:13 UTC, beforan requested changes

2020-11-30 11:58 UTC, Flemingjp commented on elastic-search/AZURE.md
> +The App Service needs to be connected to the same Virtual Network as the Elastic Search instance in order to connect to it. For an App Service, this is known as `V-Net Integration` which can be found
Cause people to use a different App Service Plan?

2020-11-30 14:19 UTC, Flemingjp commented on elastic-search/configure-search.ps1
> +$is_creation = $true ## Creates If True, Deletes If False
@beforan  Check the updated powershell script - now taking command line parameters

2020-11-30 15:06 UTC, beforan commented on elastic-search/AZURE.md
> +The App Service needs to be connected to the same Virtual Network as the Elastic Search instance in order to connect to it. For an App Service, this is known as `V-Net Integration` which can be found
cause people to use a different approach of deploying/securing elastic than the one in this guide which uses VNET integration.

2020-12-02 08:21 UTC, beforan approved these changes

2020-12-02 17:06 UTC, JosephLavagna approved these changes

2020-12-02 17:18 UTC, merged