Search Radio Buttons on Homepage Config
biobankinguk/biobankinguk pull request #63
Opened 2020-11-30 13:28 UTC by JosephLavagna

- Search radio button text on homepage is now configurable under homepage config tab

2020-11-30 13:31 UTC, beforan requested changes

2020-11-30 13:31 UTC, beforan commented on src/Directory/Biobanks.Web/Web.config
> +	  <add key="ThemeDirectory" value="~/Content/FindDx" />
this shouldn't be committed

2020-11-30 15:03 UTC, Flemingjp submitted a review, later dismissed

2020-11-30 15:22 UTC, Flemingjp approved these changes

2020-12-01 09:08 UTC, beforan approved these changes

2020-12-01 09:22 UTC, merged