Upgrade submission API to .NET 5 and Remove Join Entities
biobankinguk/biobankinguk pull request #71
Opened 2020-12-07 16:54 UTC by JosephLavagna

- Upgrade the submission API to .NET 5 
- Removed the material type/group join entity
- Does not build - Throws error relating to the Common projects EF version

2020-12-08 10:58 UTC, Flemingjp commented on src/Api/Common/Data/Entities/ReferenceData/MaterialType.cs
>          /// </summary>
Maybe worth updating the summary text for these functions - as it will become contradictory

2020-12-08 10:58 UTC, Flemingjp commented on src/Api/SubmissionApi/Services/CommitService.cs
What is the reason for the change in function - is it due to the update to .NET 5?

2020-12-08 16:45 UTC, Flemingjp submitted a review, later dismissed

2020-12-09 12:09 UTC, Flemingjp requested changes
Just the above comments

2020-12-09 13:11 UTC, JosephLavagna commented on src/Api/SubmissionApi/Services/CommitService.cs
Yep this is because of package update - the ExecuteSqlCommandAsync method was no longer available.

2020-12-09 14:33 UTC, Flemingjp approved these changes

2020-12-09 14:57 UTC, beforan requested changes

2020-12-09 14:57 UTC, beforan commented on src/Api/Common/Common.csproj
> +  <ItemGroup>
this ItemGroup can go

2020-12-09 14:57 UTC, beforan commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +	 <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
why? We aren't using any razor views, it's an API.

2020-12-09 14:57 UTC, beforan commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <VersionPrefix>3.0</VersionPrefix>
not sure who updated this to 2.1.2 but this is part of the version of the app (SubmissionApi), not anything to do with .NET or anything.

I'd prefer to use the plain `Version` property, like DECSYS does:
`<Version>2.0.0-beta.7</Version>` for example.

As for what version this is... I guess we can call it `3.0.0-alpha.1` so as not not be confusing :\

2020-12-09 14:57 UTC, beforan commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <VersionPrefix>3.0</VersionPrefix>
(since 2.1.x has already been used even though 2.0 never actually got released. that's the confusion)

2020-12-09 14:57 UTC, beforan commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <PackageReference Include="Hangfire" Version="1.7.18" />
What do we use Hangfire for in this project?!

2020-12-09 14:57 UTC, beforan commented on src/Data/SubmissionsDbContext.cs
> +        public class SubmissionsDbContextFactory : IDesignTimeDbContextFactory<SubmissionsDbContext>
don't believe this is needed, but I think you're testing the command line connection string stuff for migrations?

2020-12-09 14:57 UTC, beforan commented on src/LegacyData/LegacyData.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
if we're still using the `2.2.x` packages, we should still target `netcoreapp2.2`.

everything will go up to `3.1` when we do the Azure Functions merge later

2020-12-09 14:57 UTC, beforan commented on src/LegacyData/SubmissionsDbContext.cs
> -            model.Entity<MaterialTypeMaterialTypeGroup>()
do the webjobs use materialtype/materialtypegroups? I assume so. They will still need the join entity, since the automatic one is an ef core 5 feature...

But the join entity itself and the two entities that use it (MT and MTG) can move local to this project instead of Common. Think of it like an ef core 3.1 (or 2,2) specific override.

2020-12-09 16:18 UTC, Flemingjp commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <PackageReference Include="Hangfire" Version="1.7.18" />
It appears to be used in the `/commit` and `/reject` endpoint to queue the actual business logic as an async background task.

2020-12-09 16:20 UTC, Flemingjp commented on src/LegacyData/LegacyData.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
Would it be ideal for 3.1 now, if the Azure function is going to merge right after?

2020-12-09 16:20 UTC, beforan commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <PackageReference Include="Hangfire" Version="1.7.18" />
oh ffs. then why do we even use webjobs/az functions? why don't we just use hangfire for everything?! hmm, that violates the original design of this app somewhat. if those operations need to be background, they should have their own functions like submissionjob... We deliberately opted not to use hangfire so background tasks didn't run off the same process / server.

2020-12-09 16:21 UTC, beforan commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <PackageReference Include="Hangfire" Version="1.7.18" />
Sorry, I'm angry at the past.

2020-12-09 16:23 UTC, beforan commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <PackageReference Include="Hangfire" Version="1.7.18" />
Hangfire here may cause a problem, because the Directory today *does* use hangfire intentionally, but they may get in each other's way using the same tables... I think we need more functions. Which also means we need more queueing in az storage accounts. Also, what does the REST API give back for those endpoints? it should be 202 Accepted if the request is received but the response returns before it is actioned. Like Submit.

2020-12-09 16:23 UTC, Flemingjp commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <PackageReference Include="Hangfire" Version="1.7.18" />
Looking at the `RejectService` the logic is identical to the logic in the Azure Expiry function - with the exception of `Status.Rejected` vs `Status.Expired`

2020-12-09 16:25 UTC, Flemingjp commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <PackageReference Include="Hangfire" Version="1.7.18" />
The actions currently return `NoContent()`

2020-12-09 16:26 UTC, beforan commented on src/Data/SubmissionsDbContext.cs
> +        public class SubmissionsDbContextFactory : IDesignTimeDbContextFactory<SubmissionsDbContext>
it is still needed; we're working out the details ;)

2020-12-10 13:18 UTC, JosephLavagna commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <PackageReference Include="Hangfire" Version="1.7.18" />
@beforan @Flemingjp what's the verdict then?

2020-12-10 13:32 UTC, Flemingjp commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <PackageReference Include="Hangfire" Version="1.7.18" />
I'm assuming its going to be another Azure function - looking at the code it is identical to the current expiry function, except it marks the submission as rejected. My question is do we just duplicate the Azure expiry function and change it to a reject function - or have one function that does both with a flag (reject or expire).

Personally, I think (maybe) duplicate it, in case the behaviour diverges in the future, and keeps the purpose of the functions clear.

2020-12-10 15:33 UTC, beforan commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <PackageReference Include="Hangfire" Version="1.7.18" />
you can (probably should?) factor out the actual work piece into a service method, then have separate expiry and reject functions (in part because they are triggered differently, too) that today call the same service method, but in future it would be easy for them not to.

but yeah, expiry is timed (nightly) and reject is a queue trigger presumably, or an http trigger if you really want?

2020-12-10 15:34 UTC, beforan commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <PackageReference Include="Hangfire" Version="1.7.18" />
Agree that for this PR we can leave hangfire, having gained all this knowledge and committed to implement it in the functions PR

2020-12-10 15:41 UTC, beforan commented on src/LegacyData/LegacyData.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
yeah I think so.

2020-12-10 15:41 UTC, beforan commented on src/LegacyData/LegacyData.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
but in that case the packages should get upgraded 3.1.x ;)

2020-12-10 15:57 UTC, beforan requested changes

2020-12-10 15:57 UTC, beforan commented on src/Api/SubmissionApi/SubmissionApi.csproj
> +    <TargetFramework>netcoreapp5.0</TargetFramework>
.NET 5's target moniker is `net5.0` just to be different ;)

2020-12-11 08:55 UTC, beforan requested changes

2020-12-11 08:55 UTC, beforan commented on src/LegacyData/Entities/MaterialType.cs
> +        public ICollection<MaterialTypeGroup> MaterialTypeGroups { get; set; }
Doesn't this one need to go via the Join Entity?

2020-12-11 08:55 UTC, beforan commented on src/LegacyData/Entities/MaterialTypeGroup.cs
> +        public ICollection<MaterialType> MaterialTypes { get; set; }
Join Entity?

2020-12-11 09:06 UTC, Flemingjp approved these changes
Approved - just need fixes for the current comments

2020-12-11 10:24 UTC, Flemingjp approved these changes

2020-12-11 14:46 UTC, beforan approved these changes

2020-12-11 15:14 UTC, merged

2020-12-11 15:14 UTC, beforan commented
merging this with api builds failing under the assumption that #73 will fix it