delete biobank registration request when biobank is deleted
biobankinguk/biobankinguk pull request #72
Opened 2020-12-07 16:57 UTC by shakisparki

Allow biobank of the same name to be re-created after deletion
-  by deleting registration request as part of the process of deletion of all associated data

2020-12-08 09:43 UTC, Flemingjp approved these changes

2020-12-09 14:20 UTC, beforan requested changes

2020-12-09 14:20 UTC, beforan commented on src/Directory/Services/BiobankReadService.cs
> +            //We consider declined requests to not exist
this comment is a lie. you've removed the `DeclinedDate == null` criteria from the filter. Is that desirable? (I think so, probably). If so, remove this lying comment :P

2020-12-09 15:06 UTC, beforan approved these changes

2020-12-09 15:09 UTC, Flemingjp approved these changes

2020-12-09 15:14 UTC, merged