Submission API Azure Functions
biobankinguk/biobankinguk pull request #73
Opened 2020-12-08 10:53 UTC by Flemingjp

A single project, azure function for running two background processes for the API
- Staging submitted data from the API
- Expiring submissions of biobanks

2020-12-08 15:01 UTC, Flemingjp commented
Draft until project components upgraded to .NET 5

2020-12-14 11:17 UTC, beforan requested changes

2020-12-14 12:06 UTC, beforan approved these changes

2020-12-14 12:06 UTC, beforan commented
deferred build fix to next PR

2020-12-14 12:37 UTC, blargly approved these changes

2020-12-14 12:41 UTC, merged