API Submission DateTime Validation
biobankinguk/biobankinguk pull request #74
Opened 2020-12-08 16:50 UTC by Flemingjp

- Removed submission validation of DateTime being in the future - this validation should be done at the Staging Azure Function rather that at the submit controller

- Changed all submission payload models to use a nullable DateTime quantity, such that missing DateTime values are parsed as null, rather than a default value.

2020-12-08 16:52 UTC, Flemingjp commented on src/Api/Common/Models/DiagnosisIdModel.cs
> +        public DateTime? DateDiagnosed { get; set; }
Some models were already were marked as `[Required]`  and now are nullable type. Not sure the exact interaction here, but the generated Swagger documentation does not flag the quantity as either required or nullable. Thoughts @beforan

2020-12-09 10:10 UTC, Flemingjp commented on src/Api/SubmissionApi/Models/TreatmentSubmissionModel.cs
>          public string TreatmentLocation { get; set; }
Added `[Required]` to `TreatmentLocation` as the Swagger Documentation didn't flag this field as required, even though it is via the Submit controller validation.

2020-12-09 14:07 UTC, Flemingjp commented
Waiting on #73

2020-12-10 08:51 UTC, blargly approved these changes

2020-12-10 11:14 UTC, beforan commented on src/Api/Common/Models/DiagnosisIdModel.cs
> +        public DateTime? DateDiagnosed { get; set; }
We resolved this offline. `[Required]` nullable here provides the intended behaviour:

- nullable stops the ASP.NET ModelBinder initialising the property with the default value if it's missing from a request payload
- `[Required]` ensures we validate the presence of the property in the model; a `null` value will fail validation.

2020-12-10 11:18 UTC, beforan requested changes

2020-12-10 11:18 UTC, beforan commented on src/Api/SubmissionApi/Controllers/SubmitController.cs
> +                        else if (sampleModel.DateCreated == null)
these null checks should be redundant now as `[Required]` should catch the null values in the [ModelState check](https://github.com/biobankinguk/biobankinguk/pull/74/files#diff-e3a182992df947001a3d991380157b86671bf607d9216f6499b347515447e291R68)

Can we remove them if they're not needed?

2020-12-10 11:18 UTC, beforan commented on src/Api/SubmissionApi/Models/TreatmentSubmissionModel.cs
>          public string TreatmentLocation { get; set; }
Similarly to the dates, `[Required]` should make it caught by `ModelState.IsValid`. Is there a reason Required was left off in order to catch it in the later validation? (Does the later validation do something different?)

2020-12-10 11:43 UTC, beforan commented on src/Api/SubmissionApi/Models/TreatmentSubmissionModel.cs
>          public string TreatmentLocation { get; set; }
I mean, that was a question :P If the validation doesn't do anyting special (doesn't look like it does anything different to the dates) then `[Required]` is fine and we can remove the later validation, as `ModelState.IsValid` will do it for us, earlier, which I think is preferable...

2020-12-10 15:21 UTC, beforan approved these changes

2020-12-11 13:51 UTC, beforan approved these changes

2020-12-11 14:53 UTC, JosephLavagna approved these changes

2020-12-11 15:03 UTC, merged