Added API Submissions Azure Function Build Pipeline
biobankinguk/biobankinguk pull request #79
Opened 2020-12-14 13:30 UTC by Flemingjp

2020-12-14 15:05 UTC, beforan requested changes

2020-12-14 15:05 UTC, beforan commented on .azure/pipelines/build.api.submissions.yml
> +    - "src/Api/SubmissionAzureFunction/*"
pretty sure this should also depend on `LegacyData` and possibly `Common` and possibly an `Entities` project? Basically any project references should also be here, as changes to their code could break this app.

2020-12-15 08:50 UTC, beforan approved these changes

2020-12-15 08:52 UTC, blargly approved these changes

2020-12-15 08:52 UTC, merged