Claims replacement
biobankinguk/biobankinguk pull request #80
Opened 2020-12-14 13:48 UTC by blargly

This replaces the filter OrganisationsRoleAttribute. This called on the database 4 times every time a controller method was run, in order to populate the viewbag with biobank, network, biobank requests and network requests ID values and names.
However, this same information is queried in the custom claims manager (using the same methods), so these claims have now been expanded to include the name for the 4 types. 

Any bits of the code which previously used the viewbag for biobank Ids now looks up claims. 

Furthermore, existing bits of code that use claims need to deserialise first due to the addition of a name.

Currently, a draft as I have some thoughts on restructuring this to centralise all claims access effected by this change to use the ApplicationUserPrincipal

2020-12-14 13:57 UTC, blargly commented on src/Directory/Identity/ApplicationUserPrincipal.cs
> +        public IEnumerable<string> BiobankIds => FindAll(CustomClaimType.BiobankId).Select(x => JsonConvert.DeserializeObject<KeyValuePair<string, string>>(x.Value).Key);
Having made yet another Deserialise call I wonder if perhaps BiobankIds should be replaced with a IENumerable<KeyValuePair<int, string> Biobanks (and likewise new claims for requests) . Anywhere we then try and filter currentuser to get the correct claim types, we instead just get the user property managed here.

2020-12-14 14:03 UTC, Flemingjp commented on src/Directory/Identity/ApplicationUserPrincipal.cs
> +        public IEnumerable<string> BiobankIds => FindAll(CustomClaimType.BiobankId).Select(x => JsonConvert.DeserializeObject<KeyValuePair<string, string>>(x.Value).Key);
Is there a difference between `IEnumerable<KeyValuePair<int, string>>` vs  `Dictionary<int, string>`? Is it possible to deserialize into a `Dictionary`.

2020-12-14 14:44 UTC, beforan requested changes

2020-12-14 14:44 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/AccountController.cs
> +                    .Where(x => x.Type == CustomClaimType.BiobankId).ToList().FirstOrDefault()?.Value);
have you reused the `BiobankId` ClaimType then? Waht about the auth places where it was used previously and expects only the integer id?

2020-12-14 14:44 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/AccountController.cs
> +                if (!biobank.Equals(default(KeyValuePair<int, string>)))
I feel like it would be neater to try and get the claim first, then null check that, instead of default checking the JSON conversion.

2020-12-14 14:44 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/AccountController.cs
> +                    .Where(x => x.Type == CustomClaimType.BiobankId).ToList().FirstOrDefault()?.Value);
Also you can simplify the Claims bit to: `CurrentUser.Claims.FirstOrDefault(x => condition)`

No need to `ToList()` early (I don't believe?), and `FirstOrDefault()` accepts a filter so you don't need `Where()`.

2020-12-14 14:44 UTC, beforan commented on src/Directory/Biobanks.Web/Filters/AuthorizeAttribute.cs
> -    // TODO: what is this filter? is it used anywhere?! UserAuthorize seems to be used instead...
thanks

2020-12-14 14:44 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/AccountController.cs
>              // Single network only
I think this comment is a lie? the whole point is this works for multiple (but defaults to the first), isn't it? Or is this really only the case where they only admin one (I don't see any checks for that)

2020-12-14 14:44 UTC, beforan commented on src/Directory/Biobanks.Web/Views/Header/_NavItemBiobanks.cshtml
> +	var biobankRequestClaims = CurrentUser.Claims.Where(x => x.Type == CustomClaimType.BiobankRequestId).ToList();
Nothing gained from `ToList()`? It's only used for the `foreach` and that can do it over an `IEnumerable` quite happily.

2020-12-14 14:44 UTC, beforan commented on src/Directory/Identity/ApplicationUserPrincipal.cs
> +        public IEnumerable<string> BiobankIds => FindAll(CustomClaimType.BiobankId).Select(x => JsonConvert.DeserializeObject<KeyValuePair<string, string>>(x.Value).Key);
@blargly since these properties already exist, yeah we should probably either replace these (and update whatever uses them) or add properties that are similar but contain the id and name to the principal, so simplify the controller and view code (that you've already written :P) yeah.

@Flemingjp
- Is there a difference? yes.
- Can it be a dictionary? Probably, but I dunno is JsonConvert would do that for us or if we'd have to write code to get it to taht point, in which case it's probably not worth it. Considering the use case (e.g. nav menus) We're actually more interested in looping over them all and using both the key and the value, than we are in looking up the value for a given key. So really an array of key value pairs is closer to what we want, as well as closer to what we are dealing with (which is an array of claims containing a serialised key value pair). Blah.
- There are not duplicates of the same key. Or at least there shouldn't be

2020-12-14 14:44 UTC, beforan commented on src/Directory/Identity/Constants/CustomClaimType.cs
> +        public const string BiobankRequestId = "BiobankRequestId";
I think all these claim types need `Id` taking off the name, if they store more than just an Id.

2020-12-14 14:44 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/AccountController.cs
> +                if (!biobank.Equals(default(KeyValuePair<int, string>)))
This might get simpler anyway if the user principal provides the values rather  than deserializing here.

2021-01-11 08:42 UTC, blargly commented on src/Directory/Biobanks.Web/Controllers/AccountController.cs
> +                if (!biobank.Equals(default(KeyValuePair<int, string>)))
Yeah, this is now simplified as the deserialising happens centrally now.
As for checks, I went with using default as KeyValuePair is a struct, and will be initialised with default values for its key and value.

2021-01-11 08:45 UTC, blargly commented on src/Directory/Biobanks.Web/Controllers/AccountController.cs
>              // Single network only
Not my comment, but yes it's not right - updated with // Network admin only as its actually based on if you administer networks only.

2021-01-11 08:47 UTC, blargly commented on src/Directory/Biobanks.Web/Views/Header/_NavItemBiobanks.cshtml
> +	var biobankRequestClaims = CurrentUser.Claims.Where(x => x.Type == CustomClaimType.BiobankRequestId).ToList();
Removed (and changed anyway due to the overall centralisation of claims logic).

2021-01-11 08:49 UTC, blargly commented on src/Directory/Identity/Constants/CustomClaimType.cs
> +        public const string BiobankRequestId = "BiobankRequestId";
Agreed and done

2021-01-11 10:41 UTC, Flemingjp submitted a review, later dismissed

2021-01-11 11:56 UTC, beforan requested changes

2021-01-11 11:56 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/AccountController.cs
> +                var network = JsonConvert.DeserializeObject<KeyValuePair<int, string>>(CurrentUser.Claims
shouldn't this use CurrentUser.Networks similar to the Biobanks case above?

2021-01-11 11:56 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/ProfileController.cs
> +                if (CurrentUser.Biobanks.FirstOrDefault(x => x.Key == Convert.ToInt32(bb.OrganisationId)).Key != 0 && User.IsInRole(Role.BiobankAdmin.ToString()) ||
it's not clear what's going on here.

I _think_ it's because of the `KeyValuePair` comparison instead of the old `string`, `FirstOrDefault` won't return `null` it'll be `default(KeyValuePair)` which you noted is a struct so the Key will have `default(int)` which is `0`...

- Is `FirstOrDefault` right? should it be `SingleOrDefault` (can keys be duplicated)?
- should it use `default(int)` instead of `0`?
- Why does `OrganisationId` need converting to an `int`? Isn't it already one?
- Is it worth a comment to indicate what's going on?
- Alternatively can we rewrite it in terms of a key comparison (which is what it's doing nested inside a KVP, and closer to the previous code), which would probably make it clearer (but use slightly more code)?
e.g.
```csharp
var keys = CurrentUser.Biobanks.Select(x => x.Key);
if(keys.Contains(bb.OrganisationId)) {
  // ...
}
```

2021-01-11 11:56 UTC, beforan commented on src/Directory/Biobanks.Web/Filters/AuthoriseToAdministerCapability.cs
> +                && filterContext.RequestContext.HttpContext.User.ToApplicationUserPrincipal().Biobanks.FirstOrDefault(x => x.Key == Convert.ToInt32(activeOrganisationId)).Key != 0)
As above, this is really opaque and requires brain engagement each time!

maybe a helper method (possibly a `List<KeyValuePair<T1,T2>` Extension?) of `ContainsKey(T1 key)` would be good!

2021-01-11 11:56 UTC, beforan commented on src/Directory/Biobanks.Web/Filters/AuthoriseToAdministerCollection.cs
> +                .Biobanks.FirstOrDefault(x => x.Key == Convert.ToInt32(activeOrganisationId)).Key != 0)
same again

2021-01-11 11:56 UTC, beforan commented on src/Directory/Biobanks.Web/Filters/AuthoriseToAdministerSampleSet.cs
> +                .Biobanks.FirstOrDefault(x => x.Key == Convert.ToInt32(activeOrganisationId)).Key != 0)
again

2021-01-11 11:56 UTC, beforan commented on src/Directory/Biobanks.Web/Filters/AuthorizeAttribute.cs
> +                    if (currentUser.Biobanks.FirstOrDefault(x => x.Key == Convert.ToInt32(activeOrganisationId)).Key == 0)
revenge of the son of the same thing again, part II

2021-01-11 11:56 UTC, beforan commented on src/Directory/Biobanks.Web/Filters/AuthorizeAttribute.cs
> +                    if (currentUser.Networks.FirstOrDefault(x => x.Key == networkId).Key == 0)
and same again, though without the int conversion?

2021-01-11 11:56 UTC, beforan commented on src/Directory/Identity/ApplicationUserPrincipal.cs
> +        public IEnumerable<KeyValuePair<int, string>> Biobanks => FindAll(CustomClaimType.Biobank).Select(x => JsonConvert.DeserializeObject<KeyValuePair<int, string>>(x.Value));
Should we make these `List`? That would guarantee they are all enumerated (wastefully if they re never used), but if we already know they're going to be enumerated later (I think we do), it's better to do it just once now. That also makes the suggested ContainsKey changes above more efficient as they won't re-enumerate each time.

2021-01-11 11:56 UTC, beforan commented on src/Directory/Identity/ApplicationUserPrincipal.cs
> +        public IEnumerable<KeyValuePair<int, string>> Networks => FindAll(CustomClaimType.Network).Select(x => JsonConvert.DeserializeObject<KeyValuePair<int, string>>(x.Value));
Also probably should private helper method all of these. DeserializeJsonKeyValueClaims or something.

2021-01-19 17:28 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/AccountController.cs
> +            // Biobank admin only
huh, this *is* single biobank only, because of line 186 which checks for multiple biobanks or networks xD

2021-01-20 09:11 UTC, beforan commented on src/Directory/Biobanks.Web/Filters/AuthoriseToAdministerCapability.cs
> +            if (Convert.ToInt32(session[SessionKeys.ActiveOrganisationType]) == (int)ActiveOrganisationType.Biobank
I hate this, but I don't think there's a better way, and I hate that there's not a better way.

2021-01-20 09:17 UTC, Flemingjp approved these changes

2021-01-20 10:09 UTC, beforan requested changes

2021-01-20 10:09 UTC, beforan commented on src/Directory/Biobanks.Web/Filters/AuthoriseToAdministerCapability.cs
> +            if (Convert.ToInt32(session[SessionKeys.ActiveOrganisationType]) == (int)ActiveOrganisationType.Biobank
You know what, there *is* a slightly better way, since this is functionality is used across multiple files and is ugly every time.

Write it into an enum extension method that compares the underlying value:

```csharp
public static class EnumExtensions {
	public static bool EnumEquals<TEnum> (this TEnum enumValue, string compareValue) where TEnum : struct  {
		if(!typeof(TEnum).IsEnum) throw new ArgumentException("Expected Enum type");
		try {
			var stringAsEnumValue = (TEnum)Enum.Parse(typeof(TEnum), compareValue);
			return enumValue.Equals(stringAsEnumValue);
		} catch (ArgumentException) {
			return false;
		}
	}
	public static bool EnumEquals<TEnum> (this TEnum enumValue, int compareValue) where TEnum : struct
		=> enumValue.EnumEquals(compareValue.ToString());
}
```

the above will do it for an int value, a string of the int value, or a string of the value name:

```csharp
MyEnum.Value.EnumEquals(1);
MyEnum.Value.EnumEquals("1");
MyEnum.Value.EnumEquals("Value");

will all work and return true/false appropriately
```

2021-01-20 10:09 UTC, beforan commented on src/Directory/Biobanks.Web/Filters/AuthoriseToAdministerCapability.cs
> +            if (Convert.ToInt32(session[SessionKeys.ActiveOrganisationType]) == (int)ActiveOrganisationType.Biobank
so in context, you can do:

```csharp
ActiveOrganisationType.Biobank.EnumEquals(
  session[SessionKeys.ActiveOrganisationType]);
```

2021-01-20 10:13 UTC, beforan commented on src/Directory/Biobanks.Web/Utilities/SessionHelper.cs
>              if (Convert.ToInt32(session[SessionKeys.ActiveOrganisationType]) == (int) ActiveOrganisationType.Biobank
can use new enum extension instead, which doesn't need to string convert

2021-01-21 16:43 UTC, Flemingjp approved these changes

2021-01-21 16:58 UTC, beforan approved these changes

2021-01-21 17:01 UTC, merged