Entities Project and Harmonization
biobankinguk/biobankinguk pull request #83
Opened 2021-01-07 16:07 UTC by Flemingjp

Movement of Entities from the Directory and API into one shared Entities project.

2021-01-07 16:08 UTC, Flemingjp commented
Upto inclusive 93489bf is the structural changes to the projects. Mostly moving entities into the new project and changes / fixing references

2021-01-22 10:49 UTC, beforan requested changes

2021-01-22 10:49 UTC, beforan commented on src/Entities/Entities.csproj
> +    <RootNamespace>Entities</RootNamespace>
We ought to fix the namespace / assembly name. Probably to `Biobanks.Entities`?

The top level `Data` project also needs fixing I think, but I guess that risks a conflict with the Directory's own `Data` project.

2021-01-22 10:49 UTC, beforan commented on src/Entities/Properties/AssemblyInfo.cs
> +using System.Runtime.InteropServices;
why is this here? SDK projects don't usually generate it on disk, and the csproj has `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` (which i guess might be the cause?)

Unless something needs it, I would rather not have this file present.

2021-01-22 10:49 UTC, beforan commented on src/Entities/App.config
> +    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePer
is this file needed? don't really want provider specific stuff in this project, it should be an independent bundle of classes...

2021-01-29 10:40 UTC, beforan requested changes

2021-01-29 10:40 UTC, beforan commented on src/Directory/Biobanks.Web/Filters/OrganisationsRoleAttribute.cs
> +    public class OrganisationsRoleAttribute : FilterAttribute, IActionFilter, IResultFilter
this file was removed in #80

2021-01-29 10:40 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/SuperUserController.cs
> +            // Prevent Error Propagation When Search Index Is Down
I don't like resolving this by hiding it (the empty `catch`).

If search is down or uncontactable, we want it to log, and errors to show up in app insights etc...

not sure exactly what I want to see though.

Users probably should get a friendly message that the operation failed (rather than the stats presumably all returning 0?), but not like the current 500 error page...

2021-01-29 10:41 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/SuperUserController.cs
> +            // Prevent Error Propagation When Search Index Is Down
maybe for the sake of the PR we leave this, but be sure to create a PBI to address it

2021-02-02 09:11 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Controllers/SuperUserController.cs
> +            // Prevent Error Propagation When Search Index Is Down
PBI 30764

2021-02-02 09:31 UTC, beforan approved these changes

2021-02-02 12:06 UTC, beforan approved these changes

2021-02-02 23:18 UTC, blargly approved these changes

2021-02-02 23:18 UTC, merged