Add help links to registration pages
biobankinguk/biobankinguk pull request #84
Opened 2021-01-07 17:33 UTC by bradthompson995

Links which can be configured have been added to the registration views which show up in a alert info box for the user to see.

2021-01-15 09:33 UTC, Flemingjp requested changes

2021-01-15 09:33 UTC, Flemingjp commented on src/Directory/Data/Constants/ConfigKey.cs
Maybe have less verbose config keys ids? It not the only ones, but would stop adding anymore. My suggestions would be

`site.register.help.show` and
`site.register.help.url` 

Its a very minor point, but makes it more obvious the two keys are related

2021-01-21 13:50 UTC, Flemingjp approved these changes

2021-01-21 17:04 UTC, beforan approved these changes

2021-01-22 10:17 UTC, merged