Replace DeleteRefData method calls with API CRUD method
biobankinguk/biobankinguk pull request #89
Opened 2021-01-20 14:31 UTC by shakisparki

A lot (if not all) refdata views call upon a custom Delete{RefData} function in the ADACController rather than their existing DELETE /api/{refdata} endpoint. This should be changed so the full CRUD functionality is used.

It may also be useful to have a general function (backend or frontend) for the sucess/failure feedback messages for ADAC RefData UI. As each RefData has its own fair of method in ADACController

2021-01-20 14:37 UTC, shakisparki commented on src/Directory/Biobanks.Web/Controllers/ADACController.cs
> +        public ActionResult SetRefDataSuccessFeedbackAjax(RefDataFeedbackModel feedback)
Could also make this 3 functions for add, edit and delete and get rid of the switch case?

2021-01-20 14:57 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Scripts/ADAC/adac-access-conditions.js
> +    }
This could be moved to a new adac file as it will be used across all adac refdata scripts. Might as well try not adding any more duplication of code now

2021-01-20 14:58 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Controllers/ADACController.cs
> +        public ActionResult SetRefDataSuccessFeedbackAjax(RefDataFeedbackModel feedback)
Yepp feels like the clearer option. Could have three JavaScript functions to map across to as well.

2021-01-21 14:42 UTC, shakisparki commented on src/Directory/Biobanks.Web/Views/ADAC/AccessConditions.cshtml
> +	@Scripts.Render("~/bundles/adac/refdata-feedback")
or include this in the respective refdata bundles e.g. ( ~/bundles/adac/access-conditions)

2021-01-21 15:17 UTC, Flemingjp commented on src/Directory/Biobanks.Web/Views/ADAC/AccessConditions.cshtml
> +	@Scripts.Render("~/bundles/adac/refdata-feedback")
Good question. Bundling per ADAC bundle would prevent any issues with missing reference - either way there's going to be some duplication of the definition. I would go with adding it to the individual bundles in the BundleConfig - will be easier than changing ever view.

2021-01-26 15:39 UTC, beforan requested changes

2021-01-26 15:39 UTC, beforan commented on src/Directory/Biobanks.Web/Scripts/ADAC/adac-access-conditions.js
> +                        success: function (data, textStatus, xhr) {
can we factor this function out into a separate file, just like with `adac-refdata-feedback.js`? to avoid its repetition in EVERY ajax file. again.

2021-01-28 10:33 UTC, beforan approved these changes

2021-01-28 10:36 UTC, Flemingjp approved these changes

2021-01-28 13:26 UTC, merged