Allow publications to be disabled on a biobank level
biobankinguk/biobankinguk pull request #99
Opened 2021-02-01 19:04 UTC by shakisparki

Some Biobanks, such as AZ, have a huge number of publications due to their biobank being labelled with the company name. However, most of these publications will be matched based on name, so AZ won't want to have to go through this. Therefore, we need an option wtihin a biobank admin section to turn off publications.

2021-02-02 10:19 UTC, beforan requested changes

2021-02-02 10:19 UTC, beforan commented on src/Directory/Entity/Data/Organisation.cs
> +        public bool? IncludePublications { get; set; }
Actually I guess `null` is equivalent to `true` since that's what all your null propagation code defaults to.

Either way, in the domain, this is a true boolean, not a nullable boolean. There are two possible values, `true` or `false`. `null` is not applicable here.

Because including is the default state, however, we need to either set default to `true` in the db schema, or switch the field so it is `ExcludePublications` (so that `false` can be default).

This is cleaner, safer, better represents the intent, safes lots of null propagation code which if forgotten could cause bugs... etc...

2021-02-02 10:19 UTC, beforan commented on src/Publications/Publications/Services/Hosted/FetchPublicationsService.cs
> +            var biobanks = (await _biobankReadService.ListBiobanksAsync()).Where(x => x.IncludePublications != false).ToList();
if the property becomes a regular boolean, this comparison is simpler: `x => x.IncludePublications`

2021-02-02 10:19 UTC, beforan commented on src/Directory/Biobanks.Web/Views/Biobank/Publications.cshtml
> +        <div class="btn-group btn-toggle pull-right">
Is there a good reason we can't use a checkbox for this?

Elsewhere in the site we do for boolean toggles.

Also saves us doing all the visual state management ourselves in js. less code  = better.

2021-02-02 10:19 UTC, beforan commented on src/Directory/Biobanks.Web/Scripts/Biobank/publications.js
> +    var $onBtn = $("#on-btn");
90% of this code goes away if you use a checkbox.

2021-02-02 10:19 UTC, beforan commented on src/Directory/Biobanks.Web/Scripts/Biobank/publications.js
> +    if (btnVal)
I don't particularly like the show/hide here, but i guess it makes the most sense on the client side in a pre virtual dom world.

2021-02-02 10:19 UTC, beforan commented on src/Directory/Biobanks.Web/Controllers/BiobankController.cs
> +        public async Task<JsonResult> IncludePublicationsAjax()
can we not add any new `-Ajax` methods to web controllers that put a `success` boolean in the response body? Ideally over time we would work to eliminate the ones we already have, not add more!

The whole point of moving all the refdata admin stuff to api controllers was to avoid this. so let's continue onwards using api controller endpoints for ajax interactions.

I guess these methods will warrant a new Api Controller, for general purpose Biobank related ajax calls

They're not really RESTful, more like an RPC for a biobank setting, but that's fine. I think the route would be something like:

`/api/biobank/includepublications`
- with a GET for the current value (`true` or `false`)
- PUT to set the value with a route parameter or body payload of `true` or `false`.

Obsiously the AJAX call changes so it error handles properly on HTTP status, not the success field. also the not very clearly named "status" property is eliminated as it's a single value endpoint.

2021-02-02 14:25 UTC, shakisparki commented on src/Directory/Biobanks.Web/Views/Biobank/Publications.cshtml
> +        <div class="btn-group btn-toggle pull-right">
Ok, could you point me to where a checkbox was used?

2021-02-02 14:31 UTC, beforan commented on src/Directory/Biobanks.Web/Views/Biobank/Publications.cshtml
> +        <div class="btn-group btn-toggle pull-right">
https://github.com/biobankinguk/biobankinguk/search?l=HTML%2BRazor&q=type%3D%22checkbox%22

2021-02-04 14:59 UTC, beforan approved these changes

2021-02-05 15:25 UTC, Flemingjp approved these changes

2021-02-05 15:37 UTC, JosephLavagna approved these changes

2021-02-05 15:51 UTC, merged